# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cospan/Projects/xilinx_projects/XAPP1167_2014.4/apps/fast-corners/hardware/vivado/constrs/system_top.xdc

# Block Designs: bd/system_top/system_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_top || ORIG_REF_NAME==system_top}]

# XDC: bd/system_top/system_top_ooc.xdc
