// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "image_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int image_filter::C_S_AXI_DATA_WIDTH = "100000";
const int image_filter::C_S_AXI_WSTRB_WIDTH = "100";
const int image_filter::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic image_filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<16> image_filter::ap_const_lv16_0 = "0000000000000000";
const sc_lv<2> image_filter::ap_const_lv2_0 = "00";
const sc_lv<1> image_filter::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> image_filter::ap_const_lv32_B = "1011";
const sc_logic image_filter::ap_const_logic_0 = sc_dt::Log_0;
const bool image_filter::ap_true = true;

image_filter::image_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    image_filter_CONTROL_BUS_s_axi_U = new image_filter_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("image_filter_CONTROL_BUS_s_axi_U");
    image_filter_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    image_filter_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    image_filter_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    image_filter_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    image_filter_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    image_filter_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    image_filter_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    image_filter_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    image_filter_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    image_filter_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    image_filter_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    image_filter_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    image_filter_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    image_filter_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    image_filter_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    image_filter_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    image_filter_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    image_filter_CONTROL_BUS_s_axi_U->ACLK(ap_clk);
    image_filter_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    image_filter_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    image_filter_CONTROL_BUS_s_axi_U->rows(rows);
    image_filter_CONTROL_BUS_s_axi_U->cols(cols);
    image_filter_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    image_filter_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    image_filter_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    image_filter_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    image_filter_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    image_filter_AXIvideo2Mat_U0 = new image_filter_AXIvideo2Mat("image_filter_AXIvideo2Mat_U0");
    image_filter_AXIvideo2Mat_U0->ap_clk(ap_clk);
    image_filter_AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    image_filter_AXIvideo2Mat_U0->ap_start(image_filter_AXIvideo2Mat_U0_ap_start);
    image_filter_AXIvideo2Mat_U0->ap_done(image_filter_AXIvideo2Mat_U0_ap_done);
    image_filter_AXIvideo2Mat_U0->ap_continue(image_filter_AXIvideo2Mat_U0_ap_continue);
    image_filter_AXIvideo2Mat_U0->ap_idle(image_filter_AXIvideo2Mat_U0_ap_idle);
    image_filter_AXIvideo2Mat_U0->ap_ready(image_filter_AXIvideo2Mat_U0_ap_ready);
    image_filter_AXIvideo2Mat_U0->video_in_TDATA(video_in_TDATA);
    image_filter_AXIvideo2Mat_U0->video_in_TVALID(video_in_TVALID);
    image_filter_AXIvideo2Mat_U0->video_in_TREADY(image_filter_AXIvideo2Mat_U0_video_in_TREADY);
    image_filter_AXIvideo2Mat_U0->video_in_TKEEP(video_in_TKEEP);
    image_filter_AXIvideo2Mat_U0->video_in_TSTRB(video_in_TSTRB);
    image_filter_AXIvideo2Mat_U0->video_in_TUSER(video_in_TUSER);
    image_filter_AXIvideo2Mat_U0->video_in_TLAST(video_in_TLAST);
    image_filter_AXIvideo2Mat_U0->video_in_TID(video_in_TID);
    image_filter_AXIvideo2Mat_U0->video_in_TDEST(video_in_TDEST);
    image_filter_AXIvideo2Mat_U0->rows(image_filter_AXIvideo2Mat_U0_rows);
    image_filter_AXIvideo2Mat_U0->cols(image_filter_AXIvideo2Mat_U0_cols);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write);
    image_filter_Duplicate_U0 = new image_filter_Duplicate("image_filter_Duplicate_U0");
    image_filter_Duplicate_U0->ap_clk(ap_clk);
    image_filter_Duplicate_U0->ap_rst(ap_rst_n_inv);
    image_filter_Duplicate_U0->ap_start(image_filter_Duplicate_U0_ap_start);
    image_filter_Duplicate_U0->ap_done(image_filter_Duplicate_U0_ap_done);
    image_filter_Duplicate_U0->ap_continue(image_filter_Duplicate_U0_ap_continue);
    image_filter_Duplicate_U0->ap_idle(image_filter_Duplicate_U0_ap_idle);
    image_filter_Duplicate_U0->ap_ready(image_filter_Duplicate_U0_ap_ready);
    image_filter_Duplicate_U0->rows(image_filter_Duplicate_U0_rows);
    image_filter_Duplicate_U0->cols(image_filter_Duplicate_U0_cols);
    image_filter_Duplicate_U0->src_data_stream_0_V_dout(img_0_data_stream_0_V_dout);
    image_filter_Duplicate_U0->src_data_stream_0_V_empty_n(img_0_data_stream_0_V_empty_n);
    image_filter_Duplicate_U0->src_data_stream_0_V_read(image_filter_Duplicate_U0_src_data_stream_0_V_read);
    image_filter_Duplicate_U0->src_data_stream_1_V_dout(img_0_data_stream_1_V_dout);
    image_filter_Duplicate_U0->src_data_stream_1_V_empty_n(img_0_data_stream_1_V_empty_n);
    image_filter_Duplicate_U0->src_data_stream_1_V_read(image_filter_Duplicate_U0_src_data_stream_1_V_read);
    image_filter_Duplicate_U0->dst1_data_stream_0_V_din(image_filter_Duplicate_U0_dst1_data_stream_0_V_din);
    image_filter_Duplicate_U0->dst1_data_stream_0_V_full_n(img_1_data_stream_0_V_full_n);
    image_filter_Duplicate_U0->dst1_data_stream_0_V_write(image_filter_Duplicate_U0_dst1_data_stream_0_V_write);
    image_filter_Duplicate_U0->dst1_data_stream_1_V_din(image_filter_Duplicate_U0_dst1_data_stream_1_V_din);
    image_filter_Duplicate_U0->dst1_data_stream_1_V_full_n(img_1_data_stream_1_V_full_n);
    image_filter_Duplicate_U0->dst1_data_stream_1_V_write(image_filter_Duplicate_U0_dst1_data_stream_1_V_write);
    image_filter_Duplicate_U0->dst2_data_stream_0_V_din(image_filter_Duplicate_U0_dst2_data_stream_0_V_din);
    image_filter_Duplicate_U0->dst2_data_stream_0_V_full_n(img_1_data_stream_0_V_13_full_n);
    image_filter_Duplicate_U0->dst2_data_stream_0_V_write(image_filter_Duplicate_U0_dst2_data_stream_0_V_write);
    image_filter_Duplicate_U0->dst2_data_stream_1_V_din(image_filter_Duplicate_U0_dst2_data_stream_1_V_din);
    image_filter_Duplicate_U0->dst2_data_stream_1_V_full_n(img_1_data_stream_1_V_15_full_n);
    image_filter_Duplicate_U0->dst2_data_stream_1_V_write(image_filter_Duplicate_U0_dst2_data_stream_1_V_write);
    image_filter_Split_1080_1920_2048_0_U0 = new image_filter_Split_1080_1920_2048_0_s("image_filter_Split_1080_1920_2048_0_U0");
    image_filter_Split_1080_1920_2048_0_U0->ap_clk(ap_clk);
    image_filter_Split_1080_1920_2048_0_U0->ap_rst(ap_rst_n_inv);
    image_filter_Split_1080_1920_2048_0_U0->ap_start(image_filter_Split_1080_1920_2048_0_U0_ap_start);
    image_filter_Split_1080_1920_2048_0_U0->ap_done(image_filter_Split_1080_1920_2048_0_U0_ap_done);
    image_filter_Split_1080_1920_2048_0_U0->ap_continue(image_filter_Split_1080_1920_2048_0_U0_ap_continue);
    image_filter_Split_1080_1920_2048_0_U0->ap_idle(image_filter_Split_1080_1920_2048_0_U0_ap_idle);
    image_filter_Split_1080_1920_2048_0_U0->ap_ready(image_filter_Split_1080_1920_2048_0_U0_ap_ready);
    image_filter_Split_1080_1920_2048_0_U0->rows(image_filter_Split_1080_1920_2048_0_U0_rows);
    image_filter_Split_1080_1920_2048_0_U0->cols(image_filter_Split_1080_1920_2048_0_U0_cols);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_0_V_dout(img_1_data_stream_0_V_dout);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_0_V_empty_n(img_1_data_stream_0_V_empty_n);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_0_V_read(image_filter_Split_1080_1920_2048_0_U0_src_data_stream_0_V_read);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_1_V_dout(img_1_data_stream_1_V_dout);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_1_V_empty_n(img_1_data_stream_1_V_empty_n);
    image_filter_Split_1080_1920_2048_0_U0->src_data_stream_1_V_read(image_filter_Split_1080_1920_2048_0_U0_src_data_stream_1_V_read);
    image_filter_Split_1080_1920_2048_0_U0->dst0_data_stream_V_din(image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_din);
    image_filter_Split_1080_1920_2048_0_U0->dst0_data_stream_V_full_n(img_1_Y_data_stream_0_V_full_n);
    image_filter_Split_1080_1920_2048_0_U0->dst0_data_stream_V_write(image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_write);
    image_filter_Split_1080_1920_2048_0_U0->dst1_data_stream_V_din(image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_din);
    image_filter_Split_1080_1920_2048_0_U0->dst1_data_stream_V_full_n(img_1_UV_data_stream_0_V_full_n);
    image_filter_Split_1080_1920_2048_0_U0->dst1_data_stream_V_write(image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_write);
    image_filter_Consume_1080_1920_0_U0 = new image_filter_Consume_1080_1920_0_s("image_filter_Consume_1080_1920_0_U0");
    image_filter_Consume_1080_1920_0_U0->ap_clk(ap_clk);
    image_filter_Consume_1080_1920_0_U0->ap_rst(ap_rst_n_inv);
    image_filter_Consume_1080_1920_0_U0->ap_start(image_filter_Consume_1080_1920_0_U0_ap_start);
    image_filter_Consume_1080_1920_0_U0->ap_done(image_filter_Consume_1080_1920_0_U0_ap_done);
    image_filter_Consume_1080_1920_0_U0->ap_continue(image_filter_Consume_1080_1920_0_U0_ap_continue);
    image_filter_Consume_1080_1920_0_U0->ap_idle(image_filter_Consume_1080_1920_0_U0_ap_idle);
    image_filter_Consume_1080_1920_0_U0->ap_ready(image_filter_Consume_1080_1920_0_U0_ap_ready);
    image_filter_Consume_1080_1920_0_U0->rows(image_filter_Consume_1080_1920_0_U0_rows);
    image_filter_Consume_1080_1920_0_U0->cols(image_filter_Consume_1080_1920_0_U0_cols);
    image_filter_Consume_1080_1920_0_U0->src_data_stream_V_dout(img_1_UV_data_stream_0_V_dout);
    image_filter_Consume_1080_1920_0_U0->src_data_stream_V_empty_n(img_1_UV_data_stream_0_V_empty_n);
    image_filter_Consume_1080_1920_0_U0->src_data_stream_V_read(image_filter_Consume_1080_1920_0_U0_src_data_stream_V_read);
    image_filter_FAST_t_opr_U0 = new image_filter_FAST_t_opr("image_filter_FAST_t_opr_U0");
    image_filter_FAST_t_opr_U0->ap_clk(ap_clk);
    image_filter_FAST_t_opr_U0->ap_rst(ap_rst_n_inv);
    image_filter_FAST_t_opr_U0->ap_start(image_filter_FAST_t_opr_U0_ap_start);
    image_filter_FAST_t_opr_U0->ap_done(image_filter_FAST_t_opr_U0_ap_done);
    image_filter_FAST_t_opr_U0->ap_continue(image_filter_FAST_t_opr_U0_ap_continue);
    image_filter_FAST_t_opr_U0->ap_idle(image_filter_FAST_t_opr_U0_ap_idle);
    image_filter_FAST_t_opr_U0->ap_ready(image_filter_FAST_t_opr_U0_ap_ready);
    image_filter_FAST_t_opr_U0->rows(image_filter_FAST_t_opr_U0_rows);
    image_filter_FAST_t_opr_U0->cols(image_filter_FAST_t_opr_U0_cols);
    image_filter_FAST_t_opr_U0->p_src_data_stream_V_dout(img_1_Y_data_stream_0_V_dout);
    image_filter_FAST_t_opr_U0->p_src_data_stream_V_empty_n(img_1_Y_data_stream_0_V_empty_n);
    image_filter_FAST_t_opr_U0->p_src_data_stream_V_read(image_filter_FAST_t_opr_U0_p_src_data_stream_V_read);
    image_filter_FAST_t_opr_U0->p_mask_data_stream_V_din(image_filter_FAST_t_opr_U0_p_mask_data_stream_V_din);
    image_filter_FAST_t_opr_U0->p_mask_data_stream_V_full_n(mask_data_stream_0_V_full_n);
    image_filter_FAST_t_opr_U0->p_mask_data_stream_V_write(image_filter_FAST_t_opr_U0_p_mask_data_stream_V_write);
    image_filter_Dilate_0_0_1080_1920_U0 = new image_filter_Dilate_0_0_1080_1920_s("image_filter_Dilate_0_0_1080_1920_U0");
    image_filter_Dilate_0_0_1080_1920_U0->ap_clk(ap_clk);
    image_filter_Dilate_0_0_1080_1920_U0->ap_rst(ap_rst_n_inv);
    image_filter_Dilate_0_0_1080_1920_U0->ap_start(image_filter_Dilate_0_0_1080_1920_U0_ap_start);
    image_filter_Dilate_0_0_1080_1920_U0->ap_done(image_filter_Dilate_0_0_1080_1920_U0_ap_done);
    image_filter_Dilate_0_0_1080_1920_U0->ap_continue(image_filter_Dilate_0_0_1080_1920_U0_ap_continue);
    image_filter_Dilate_0_0_1080_1920_U0->ap_idle(image_filter_Dilate_0_0_1080_1920_U0_ap_idle);
    image_filter_Dilate_0_0_1080_1920_U0->ap_ready(image_filter_Dilate_0_0_1080_1920_U0_ap_ready);
    image_filter_Dilate_0_0_1080_1920_U0->rows(image_filter_Dilate_0_0_1080_1920_U0_rows);
    image_filter_Dilate_0_0_1080_1920_U0->cols(image_filter_Dilate_0_0_1080_1920_U0_cols);
    image_filter_Dilate_0_0_1080_1920_U0->p_src_data_stream_V_dout(mask_data_stream_0_V_dout);
    image_filter_Dilate_0_0_1080_1920_U0->p_src_data_stream_V_empty_n(mask_data_stream_0_V_empty_n);
    image_filter_Dilate_0_0_1080_1920_U0->p_src_data_stream_V_read(image_filter_Dilate_0_0_1080_1920_U0_p_src_data_stream_V_read);
    image_filter_Dilate_0_0_1080_1920_U0->p_dst_data_stream_V_din(image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_din);
    image_filter_Dilate_0_0_1080_1920_U0->p_dst_data_stream_V_full_n(dmask_data_stream_0_V_full_n);
    image_filter_Dilate_0_0_1080_1920_U0->p_dst_data_stream_V_write(image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_write);
    image_filter_PaintMask_2048_0_1080_1920_U0 = new image_filter_PaintMask_2048_0_1080_1920_s("image_filter_PaintMask_2048_0_1080_1920_U0");
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_clk(ap_clk);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_rst(ap_rst_n_inv);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_start(image_filter_PaintMask_2048_0_1080_1920_U0_ap_start);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_done(image_filter_PaintMask_2048_0_1080_1920_U0_ap_done);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_continue(image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_idle(image_filter_PaintMask_2048_0_1080_1920_U0_ap_idle);
    image_filter_PaintMask_2048_0_1080_1920_U0->ap_ready(image_filter_PaintMask_2048_0_1080_1920_U0_ap_ready);
    image_filter_PaintMask_2048_0_1080_1920_U0->rows(image_filter_PaintMask_2048_0_1080_1920_U0_rows);
    image_filter_PaintMask_2048_0_1080_1920_U0->cols(image_filter_PaintMask_2048_0_1080_1920_U0_cols);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_0_V_dout(img_1_data_stream_0_V_13_dout);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_0_V_empty_n(img_1_data_stream_0_V_13_empty_n);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_0_V_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_0_V_read);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_1_V_dout(img_1_data_stream_1_V_15_dout);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_1_V_empty_n(img_1_data_stream_1_V_15_empty_n);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_src_data_stream_1_V_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_1_V_read);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_mask_data_stream_V_dout(dmask_data_stream_0_V_dout);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_mask_data_stream_V_empty_n(dmask_data_stream_0_V_empty_n);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_mask_data_stream_V_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_mask_data_stream_V_read);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_0_V_din(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_din);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_0_V_full_n(img_2_data_stream_0_V_full_n);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_0_V_write(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_write);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_1_V_din(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_din);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_1_V_full_n(img_2_data_stream_1_V_full_n);
    image_filter_PaintMask_2048_0_1080_1920_U0->p_dst_data_stream_1_V_write(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_write);
    image_filter_Mat2AXIvideo_U0 = new image_filter_Mat2AXIvideo("image_filter_Mat2AXIvideo_U0");
    image_filter_Mat2AXIvideo_U0->ap_clk(ap_clk);
    image_filter_Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    image_filter_Mat2AXIvideo_U0->ap_start(image_filter_Mat2AXIvideo_U0_ap_start);
    image_filter_Mat2AXIvideo_U0->ap_done(image_filter_Mat2AXIvideo_U0_ap_done);
    image_filter_Mat2AXIvideo_U0->ap_continue(image_filter_Mat2AXIvideo_U0_ap_continue);
    image_filter_Mat2AXIvideo_U0->ap_idle(image_filter_Mat2AXIvideo_U0_ap_idle);
    image_filter_Mat2AXIvideo_U0->ap_ready(image_filter_Mat2AXIvideo_U0_ap_ready);
    image_filter_Mat2AXIvideo_U0->rows(image_filter_Mat2AXIvideo_U0_rows);
    image_filter_Mat2AXIvideo_U0->cols(image_filter_Mat2AXIvideo_U0_cols);
    image_filter_Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_2_data_stream_0_V_dout);
    image_filter_Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_2_data_stream_0_V_empty_n);
    image_filter_Mat2AXIvideo_U0->img_data_stream_0_V_read(image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read);
    image_filter_Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_2_data_stream_1_V_dout);
    image_filter_Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_2_data_stream_1_V_empty_n);
    image_filter_Mat2AXIvideo_U0->img_data_stream_1_V_read(image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read);
    image_filter_Mat2AXIvideo_U0->video_out_TDATA(image_filter_Mat2AXIvideo_U0_video_out_TDATA);
    image_filter_Mat2AXIvideo_U0->video_out_TVALID(image_filter_Mat2AXIvideo_U0_video_out_TVALID);
    image_filter_Mat2AXIvideo_U0->video_out_TREADY(video_out_TREADY);
    image_filter_Mat2AXIvideo_U0->video_out_TKEEP(image_filter_Mat2AXIvideo_U0_video_out_TKEEP);
    image_filter_Mat2AXIvideo_U0->video_out_TSTRB(image_filter_Mat2AXIvideo_U0_video_out_TSTRB);
    image_filter_Mat2AXIvideo_U0->video_out_TUSER(image_filter_Mat2AXIvideo_U0_video_out_TUSER);
    image_filter_Mat2AXIvideo_U0->video_out_TLAST(image_filter_Mat2AXIvideo_U0_video_out_TLAST);
    image_filter_Mat2AXIvideo_U0->video_out_TID(image_filter_Mat2AXIvideo_U0_video_out_TID);
    image_filter_Mat2AXIvideo_U0->video_out_TDEST(image_filter_Mat2AXIvideo_U0_video_out_TDEST);
    img_0_data_stream_0_V_U = new FIFO_image_filter_img_0_data_stream_0_V("img_0_data_stream_0_V_U");
    img_0_data_stream_0_V_U->clk(ap_clk);
    img_0_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_V_U->if_din(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_V_U->if_full_n(img_0_data_stream_0_V_full_n);
    img_0_data_stream_0_V_U->if_write(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_V_U->if_dout(img_0_data_stream_0_V_dout);
    img_0_data_stream_0_V_U->if_empty_n(img_0_data_stream_0_V_empty_n);
    img_0_data_stream_0_V_U->if_read(image_filter_Duplicate_U0_src_data_stream_0_V_read);
    img_0_data_stream_1_V_U = new FIFO_image_filter_img_0_data_stream_1_V("img_0_data_stream_1_V_U");
    img_0_data_stream_1_V_U->clk(ap_clk);
    img_0_data_stream_1_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_V_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_V_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_V_U->if_din(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_V_U->if_full_n(img_0_data_stream_1_V_full_n);
    img_0_data_stream_1_V_U->if_write(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_V_U->if_dout(img_0_data_stream_1_V_dout);
    img_0_data_stream_1_V_U->if_empty_n(img_0_data_stream_1_V_empty_n);
    img_0_data_stream_1_V_U->if_read(image_filter_Duplicate_U0_src_data_stream_1_V_read);
    img_1_data_stream_0_V_U = new FIFO_image_filter_img_1_data_stream_0_V("img_1_data_stream_0_V_U");
    img_1_data_stream_0_V_U->clk(ap_clk);
    img_1_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_V_U->if_din(image_filter_Duplicate_U0_dst1_data_stream_0_V_din);
    img_1_data_stream_0_V_U->if_full_n(img_1_data_stream_0_V_full_n);
    img_1_data_stream_0_V_U->if_write(image_filter_Duplicate_U0_dst1_data_stream_0_V_write);
    img_1_data_stream_0_V_U->if_dout(img_1_data_stream_0_V_dout);
    img_1_data_stream_0_V_U->if_empty_n(img_1_data_stream_0_V_empty_n);
    img_1_data_stream_0_V_U->if_read(image_filter_Split_1080_1920_2048_0_U0_src_data_stream_0_V_read);
    img_1_data_stream_1_V_U = new FIFO_image_filter_img_1_data_stream_1_V("img_1_data_stream_1_V_U");
    img_1_data_stream_1_V_U->clk(ap_clk);
    img_1_data_stream_1_V_U->reset(ap_rst_n_inv);
    img_1_data_stream_1_V_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_1_V_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_1_V_U->if_din(image_filter_Duplicate_U0_dst1_data_stream_1_V_din);
    img_1_data_stream_1_V_U->if_full_n(img_1_data_stream_1_V_full_n);
    img_1_data_stream_1_V_U->if_write(image_filter_Duplicate_U0_dst1_data_stream_1_V_write);
    img_1_data_stream_1_V_U->if_dout(img_1_data_stream_1_V_dout);
    img_1_data_stream_1_V_U->if_empty_n(img_1_data_stream_1_V_empty_n);
    img_1_data_stream_1_V_U->if_read(image_filter_Split_1080_1920_2048_0_U0_src_data_stream_1_V_read);
    img_1_data_stream_0_V_13_U = new FIFO_image_filter_img_1_data_stream_0_V_13("img_1_data_stream_0_V_13_U");
    img_1_data_stream_0_V_13_U->clk(ap_clk);
    img_1_data_stream_0_V_13_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_V_13_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_V_13_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_V_13_U->if_din(image_filter_Duplicate_U0_dst2_data_stream_0_V_din);
    img_1_data_stream_0_V_13_U->if_full_n(img_1_data_stream_0_V_13_full_n);
    img_1_data_stream_0_V_13_U->if_write(image_filter_Duplicate_U0_dst2_data_stream_0_V_write);
    img_1_data_stream_0_V_13_U->if_dout(img_1_data_stream_0_V_13_dout);
    img_1_data_stream_0_V_13_U->if_empty_n(img_1_data_stream_0_V_13_empty_n);
    img_1_data_stream_0_V_13_U->if_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_0_V_read);
    img_1_data_stream_1_V_15_U = new FIFO_image_filter_img_1_data_stream_1_V_15("img_1_data_stream_1_V_15_U");
    img_1_data_stream_1_V_15_U->clk(ap_clk);
    img_1_data_stream_1_V_15_U->reset(ap_rst_n_inv);
    img_1_data_stream_1_V_15_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_1_V_15_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_1_V_15_U->if_din(image_filter_Duplicate_U0_dst2_data_stream_1_V_din);
    img_1_data_stream_1_V_15_U->if_full_n(img_1_data_stream_1_V_15_full_n);
    img_1_data_stream_1_V_15_U->if_write(image_filter_Duplicate_U0_dst2_data_stream_1_V_write);
    img_1_data_stream_1_V_15_U->if_dout(img_1_data_stream_1_V_15_dout);
    img_1_data_stream_1_V_15_U->if_empty_n(img_1_data_stream_1_V_15_empty_n);
    img_1_data_stream_1_V_15_U->if_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_1_V_read);
    img_1_Y_data_stream_0_V_U = new FIFO_image_filter_img_1_Y_data_stream_0_V("img_1_Y_data_stream_0_V_U");
    img_1_Y_data_stream_0_V_U->clk(ap_clk);
    img_1_Y_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_1_Y_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    img_1_Y_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    img_1_Y_data_stream_0_V_U->if_din(image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_din);
    img_1_Y_data_stream_0_V_U->if_full_n(img_1_Y_data_stream_0_V_full_n);
    img_1_Y_data_stream_0_V_U->if_write(image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_write);
    img_1_Y_data_stream_0_V_U->if_dout(img_1_Y_data_stream_0_V_dout);
    img_1_Y_data_stream_0_V_U->if_empty_n(img_1_Y_data_stream_0_V_empty_n);
    img_1_Y_data_stream_0_V_U->if_read(image_filter_FAST_t_opr_U0_p_src_data_stream_V_read);
    img_1_UV_data_stream_0_V_U = new FIFO_image_filter_img_1_UV_data_stream_0_V("img_1_UV_data_stream_0_V_U");
    img_1_UV_data_stream_0_V_U->clk(ap_clk);
    img_1_UV_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_1_UV_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    img_1_UV_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    img_1_UV_data_stream_0_V_U->if_din(image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_din);
    img_1_UV_data_stream_0_V_U->if_full_n(img_1_UV_data_stream_0_V_full_n);
    img_1_UV_data_stream_0_V_U->if_write(image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_write);
    img_1_UV_data_stream_0_V_U->if_dout(img_1_UV_data_stream_0_V_dout);
    img_1_UV_data_stream_0_V_U->if_empty_n(img_1_UV_data_stream_0_V_empty_n);
    img_1_UV_data_stream_0_V_U->if_read(image_filter_Consume_1080_1920_0_U0_src_data_stream_V_read);
    mask_data_stream_0_V_U = new FIFO_image_filter_mask_data_stream_0_V("mask_data_stream_0_V_U");
    mask_data_stream_0_V_U->clk(ap_clk);
    mask_data_stream_0_V_U->reset(ap_rst_n_inv);
    mask_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    mask_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    mask_data_stream_0_V_U->if_din(image_filter_FAST_t_opr_U0_p_mask_data_stream_V_din);
    mask_data_stream_0_V_U->if_full_n(mask_data_stream_0_V_full_n);
    mask_data_stream_0_V_U->if_write(image_filter_FAST_t_opr_U0_p_mask_data_stream_V_write);
    mask_data_stream_0_V_U->if_dout(mask_data_stream_0_V_dout);
    mask_data_stream_0_V_U->if_empty_n(mask_data_stream_0_V_empty_n);
    mask_data_stream_0_V_U->if_read(image_filter_Dilate_0_0_1080_1920_U0_p_src_data_stream_V_read);
    dmask_data_stream_0_V_U = new FIFO_image_filter_dmask_data_stream_0_V("dmask_data_stream_0_V_U");
    dmask_data_stream_0_V_U->clk(ap_clk);
    dmask_data_stream_0_V_U->reset(ap_rst_n_inv);
    dmask_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    dmask_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    dmask_data_stream_0_V_U->if_din(image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_din);
    dmask_data_stream_0_V_U->if_full_n(dmask_data_stream_0_V_full_n);
    dmask_data_stream_0_V_U->if_write(image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_write);
    dmask_data_stream_0_V_U->if_dout(dmask_data_stream_0_V_dout);
    dmask_data_stream_0_V_U->if_empty_n(dmask_data_stream_0_V_empty_n);
    dmask_data_stream_0_V_U->if_read(image_filter_PaintMask_2048_0_1080_1920_U0_p_mask_data_stream_V_read);
    img_2_data_stream_0_V_U = new FIFO_image_filter_img_2_data_stream_0_V("img_2_data_stream_0_V_U");
    img_2_data_stream_0_V_U->clk(ap_clk);
    img_2_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_2_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    img_2_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    img_2_data_stream_0_V_U->if_din(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_din);
    img_2_data_stream_0_V_U->if_full_n(img_2_data_stream_0_V_full_n);
    img_2_data_stream_0_V_U->if_write(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_write);
    img_2_data_stream_0_V_U->if_dout(img_2_data_stream_0_V_dout);
    img_2_data_stream_0_V_U->if_empty_n(img_2_data_stream_0_V_empty_n);
    img_2_data_stream_0_V_U->if_read(image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_2_data_stream_1_V_U = new FIFO_image_filter_img_2_data_stream_1_V("img_2_data_stream_1_V_U");
    img_2_data_stream_1_V_U->clk(ap_clk);
    img_2_data_stream_1_V_U->reset(ap_rst_n_inv);
    img_2_data_stream_1_V_U->if_read_ce(ap_var_for_const0);
    img_2_data_stream_1_V_U->if_write_ce(ap_var_for_const0);
    img_2_data_stream_1_V_U->if_din(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_din);
    img_2_data_stream_1_V_U->if_full_n(img_2_data_stream_1_V_full_n);
    img_2_data_stream_1_V_U->if_write(image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_write);
    img_2_data_stream_1_V_U->if_dout(img_2_data_stream_1_V_dout);
    img_2_data_stream_1_V_U->if_empty_n(img_2_data_stream_1_V_empty_n);
    img_2_data_stream_1_V_U->if_read(image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_idle );
    sensitive << ( image_filter_Duplicate_U0_ap_idle );
    sensitive << ( image_filter_Split_1080_1920_2048_0_U0_ap_idle );
    sensitive << ( image_filter_Consume_1080_1920_0_U0_ap_idle );
    sensitive << ( image_filter_FAST_t_opr_U0_ap_idle );
    sensitive << ( image_filter_Dilate_0_0_1080_1920_U0_ap_idle );
    sensitive << ( image_filter_PaintMask_2048_0_1080_1920_U0_ap_idle );
    sensitive << ( image_filter_Mat2AXIvideo_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( image_filter_Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sig_hs_ready);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Consume_1080_1920_0_U0_ap_continue);

    SC_METHOD(thread_image_filter_Consume_1080_1920_0_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Consume_1080_1920_0_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Consume_1080_1920_0_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Dilate_0_0_1080_1920_U0_ap_continue);

    SC_METHOD(thread_image_filter_Dilate_0_0_1080_1920_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Dilate_0_0_1080_1920_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Dilate_0_0_1080_1920_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Duplicate_U0_ap_continue);

    SC_METHOD(thread_image_filter_Duplicate_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Duplicate_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Duplicate_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_FAST_t_opr_U0_ap_continue);

    SC_METHOD(thread_image_filter_FAST_t_opr_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_FAST_t_opr_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_FAST_t_opr_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue);

    SC_METHOD(thread_image_filter_PaintMask_2048_0_1080_1920_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_PaintMask_2048_0_1080_1920_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_PaintMask_2048_0_1080_1920_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Split_1080_1920_2048_0_U0_ap_continue);

    SC_METHOD(thread_image_filter_Split_1080_1920_2048_0_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Split_1080_1920_2048_0_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Split_1080_1920_2048_0_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_video_in_TREADY);
    sensitive << ( image_filter_AXIvideo2Mat_U0_video_in_TREADY );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TDATA );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TDEST );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TID );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TKEEP );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TLAST );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TSTRB );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TUSER );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( image_filter_Mat2AXIvideo_U0_video_out_TVALID );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, video_in_TDATA, "(port)video_in_TDATA");
    sc_trace(mVcdFile, video_in_TKEEP, "(port)video_in_TKEEP");
    sc_trace(mVcdFile, video_in_TSTRB, "(port)video_in_TSTRB");
    sc_trace(mVcdFile, video_in_TUSER, "(port)video_in_TUSER");
    sc_trace(mVcdFile, video_in_TLAST, "(port)video_in_TLAST");
    sc_trace(mVcdFile, video_in_TID, "(port)video_in_TID");
    sc_trace(mVcdFile, video_in_TDEST, "(port)video_in_TDEST");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
    sc_trace(mVcdFile, video_in_TVALID, "(port)video_in_TVALID");
    sc_trace(mVcdFile, video_in_TREADY, "(port)video_in_TREADY");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, rows, "rows");
    sc_trace(mVcdFile, cols, "cols");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_start, "image_filter_AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_done, "image_filter_AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_continue, "image_filter_AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_idle, "image_filter_AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_ready, "image_filter_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_video_in_TREADY, "image_filter_AXIvideo2Mat_U0_video_in_TREADY");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_rows, "image_filter_AXIvideo2Mat_U0_rows");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_cols, "image_filter_AXIvideo2Mat_U0_cols");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_ap_start, "image_filter_Duplicate_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_ap_done, "image_filter_Duplicate_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_ap_continue, "image_filter_Duplicate_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_ap_idle, "image_filter_Duplicate_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_ap_ready, "image_filter_Duplicate_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_rows, "image_filter_Duplicate_U0_rows");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_cols, "image_filter_Duplicate_U0_cols");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_src_data_stream_0_V_read, "image_filter_Duplicate_U0_src_data_stream_0_V_read");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_src_data_stream_1_V_read, "image_filter_Duplicate_U0_src_data_stream_1_V_read");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst1_data_stream_0_V_din, "image_filter_Duplicate_U0_dst1_data_stream_0_V_din");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst1_data_stream_0_V_write, "image_filter_Duplicate_U0_dst1_data_stream_0_V_write");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst1_data_stream_1_V_din, "image_filter_Duplicate_U0_dst1_data_stream_1_V_din");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst1_data_stream_1_V_write, "image_filter_Duplicate_U0_dst1_data_stream_1_V_write");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst2_data_stream_0_V_din, "image_filter_Duplicate_U0_dst2_data_stream_0_V_din");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst2_data_stream_0_V_write, "image_filter_Duplicate_U0_dst2_data_stream_0_V_write");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst2_data_stream_1_V_din, "image_filter_Duplicate_U0_dst2_data_stream_1_V_din");
    sc_trace(mVcdFile, image_filter_Duplicate_U0_dst2_data_stream_1_V_write, "image_filter_Duplicate_U0_dst2_data_stream_1_V_write");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_ap_start, "image_filter_Split_1080_1920_2048_0_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_ap_done, "image_filter_Split_1080_1920_2048_0_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_ap_continue, "image_filter_Split_1080_1920_2048_0_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_ap_idle, "image_filter_Split_1080_1920_2048_0_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_ap_ready, "image_filter_Split_1080_1920_2048_0_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_rows, "image_filter_Split_1080_1920_2048_0_U0_rows");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_cols, "image_filter_Split_1080_1920_2048_0_U0_cols");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_src_data_stream_0_V_read, "image_filter_Split_1080_1920_2048_0_U0_src_data_stream_0_V_read");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_src_data_stream_1_V_read, "image_filter_Split_1080_1920_2048_0_U0_src_data_stream_1_V_read");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_din, "image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_write, "image_filter_Split_1080_1920_2048_0_U0_dst0_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_din, "image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_write, "image_filter_Split_1080_1920_2048_0_U0_dst1_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_ap_start, "image_filter_Consume_1080_1920_0_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_ap_done, "image_filter_Consume_1080_1920_0_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_ap_continue, "image_filter_Consume_1080_1920_0_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_ap_idle, "image_filter_Consume_1080_1920_0_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_ap_ready, "image_filter_Consume_1080_1920_0_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_rows, "image_filter_Consume_1080_1920_0_U0_rows");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_cols, "image_filter_Consume_1080_1920_0_U0_cols");
    sc_trace(mVcdFile, image_filter_Consume_1080_1920_0_U0_src_data_stream_V_read, "image_filter_Consume_1080_1920_0_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_ap_start, "image_filter_FAST_t_opr_U0_ap_start");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_ap_done, "image_filter_FAST_t_opr_U0_ap_done");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_ap_continue, "image_filter_FAST_t_opr_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_ap_idle, "image_filter_FAST_t_opr_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_ap_ready, "image_filter_FAST_t_opr_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_rows, "image_filter_FAST_t_opr_U0_rows");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_cols, "image_filter_FAST_t_opr_U0_cols");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_p_src_data_stream_V_read, "image_filter_FAST_t_opr_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_p_mask_data_stream_V_din, "image_filter_FAST_t_opr_U0_p_mask_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_FAST_t_opr_U0_p_mask_data_stream_V_write, "image_filter_FAST_t_opr_U0_p_mask_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_ap_start, "image_filter_Dilate_0_0_1080_1920_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_ap_done, "image_filter_Dilate_0_0_1080_1920_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_ap_continue, "image_filter_Dilate_0_0_1080_1920_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_ap_idle, "image_filter_Dilate_0_0_1080_1920_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_ap_ready, "image_filter_Dilate_0_0_1080_1920_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_rows, "image_filter_Dilate_0_0_1080_1920_U0_rows");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_cols, "image_filter_Dilate_0_0_1080_1920_U0_cols");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_p_src_data_stream_V_read, "image_filter_Dilate_0_0_1080_1920_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_din, "image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_write, "image_filter_Dilate_0_0_1080_1920_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_ap_start, "image_filter_PaintMask_2048_0_1080_1920_U0_ap_start");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_ap_done, "image_filter_PaintMask_2048_0_1080_1920_U0_ap_done");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue, "image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_ap_idle, "image_filter_PaintMask_2048_0_1080_1920_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_ap_ready, "image_filter_PaintMask_2048_0_1080_1920_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_rows, "image_filter_PaintMask_2048_0_1080_1920_U0_rows");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_cols, "image_filter_PaintMask_2048_0_1080_1920_U0_cols");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_0_V_read, "image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_1_V_read, "image_filter_PaintMask_2048_0_1080_1920_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_mask_data_stream_V_read, "image_filter_PaintMask_2048_0_1080_1920_U0_p_mask_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_din, "image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_write, "image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_din, "image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_write, "image_filter_PaintMask_2048_0_1080_1920_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_start, "image_filter_Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_done, "image_filter_Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_continue, "image_filter_Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_idle, "image_filter_Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_ap_ready, "image_filter_Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_rows, "image_filter_Mat2AXIvideo_U0_rows");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_cols, "image_filter_Mat2AXIvideo_U0_cols");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read, "image_filter_Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read, "image_filter_Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TDATA, "image_filter_Mat2AXIvideo_U0_video_out_TDATA");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TVALID, "image_filter_Mat2AXIvideo_U0_video_out_TVALID");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TKEEP, "image_filter_Mat2AXIvideo_U0_video_out_TKEEP");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TSTRB, "image_filter_Mat2AXIvideo_U0_video_out_TSTRB");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TUSER, "image_filter_Mat2AXIvideo_U0_video_out_TUSER");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TLAST, "image_filter_Mat2AXIvideo_U0_video_out_TLAST");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TID, "image_filter_Mat2AXIvideo_U0_video_out_TID");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_U0_video_out_TDEST, "image_filter_Mat2AXIvideo_U0_video_out_TDEST");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, img_0_data_stream_0_V_full_n, "img_0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_dout, "img_0_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_V_empty_n, "img_0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_full_n, "img_0_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_dout, "img_0_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_V_empty_n, "img_0_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_full_n, "img_1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_dout, "img_1_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_V_empty_n, "img_1_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_1_V_full_n, "img_1_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_V_dout, "img_1_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_1_data_stream_1_V_empty_n, "img_1_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_13_full_n, "img_1_data_stream_0_V_13_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_13_dout, "img_1_data_stream_0_V_13_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_V_13_empty_n, "img_1_data_stream_0_V_13_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_1_V_15_full_n, "img_1_data_stream_1_V_15_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_V_15_dout, "img_1_data_stream_1_V_15_dout");
    sc_trace(mVcdFile, img_1_data_stream_1_V_15_empty_n, "img_1_data_stream_1_V_15_empty_n");
    sc_trace(mVcdFile, img_1_Y_data_stream_0_V_full_n, "img_1_Y_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_Y_data_stream_0_V_dout, "img_1_Y_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_Y_data_stream_0_V_empty_n, "img_1_Y_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_1_UV_data_stream_0_V_full_n, "img_1_UV_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_UV_data_stream_0_V_dout, "img_1_UV_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_UV_data_stream_0_V_empty_n, "img_1_UV_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, mask_data_stream_0_V_full_n, "mask_data_stream_0_V_full_n");
    sc_trace(mVcdFile, mask_data_stream_0_V_dout, "mask_data_stream_0_V_dout");
    sc_trace(mVcdFile, mask_data_stream_0_V_empty_n, "mask_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, dmask_data_stream_0_V_full_n, "dmask_data_stream_0_V_full_n");
    sc_trace(mVcdFile, dmask_data_stream_0_V_dout, "dmask_data_stream_0_V_dout");
    sc_trace(mVcdFile, dmask_data_stream_0_V_empty_n, "dmask_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_full_n, "img_2_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_dout, "img_2_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_V_empty_n, "img_2_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_1_V_full_n, "img_2_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_2_data_stream_1_V_dout, "img_2_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_2_data_stream_1_V_empty_n, "img_2_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_sig_hs_ready, "ap_sig_hs_ready");
#endif

    }
    mHdltvinHandle.open("image_filter.hdltvin.dat");
    mHdltvoutHandle.open("image_filter.hdltvout.dat");
}

image_filter::~image_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete image_filter_CONTROL_BUS_s_axi_U;
    delete image_filter_AXIvideo2Mat_U0;
    delete image_filter_Duplicate_U0;
    delete image_filter_Split_1080_1920_2048_0_U0;
    delete image_filter_Consume_1080_1920_0_U0;
    delete image_filter_FAST_t_opr_U0;
    delete image_filter_Dilate_0_0_1080_1920_U0;
    delete image_filter_PaintMask_2048_0_1080_1920_U0;
    delete image_filter_Mat2AXIvideo_U0;
    delete img_0_data_stream_0_V_U;
    delete img_0_data_stream_1_V_U;
    delete img_1_data_stream_0_V_U;
    delete img_1_data_stream_1_V_U;
    delete img_1_data_stream_0_V_13_U;
    delete img_1_data_stream_1_V_15_U;
    delete img_1_Y_data_stream_0_V_U;
    delete img_1_UV_data_stream_0_V_U;
    delete mask_data_stream_0_V_U;
    delete dmask_data_stream_0_V_U;
    delete img_2_data_stream_0_V_U;
    delete img_2_data_stream_1_V_U;
}

void image_filter::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void image_filter::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void image_filter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, image_filter_AXIvideo2Mat_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Duplicate_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Split_1080_1920_2048_0_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Consume_1080_1920_0_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_FAST_t_opr_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Dilate_0_0_1080_1920_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_PaintMask_2048_0_1080_1920_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_U0_ap_idle.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter::thread_ap_ready() {
    ap_ready = image_filter_AXIvideo2Mat_U0_ap_ready.read();
}

void image_filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void image_filter::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void image_filter::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void image_filter::thread_ap_sig_hs_ready() {
    ap_sig_hs_ready = image_filter_AXIvideo2Mat_U0_ap_ready.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_continue() {
    image_filter_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_start() {
    image_filter_AXIvideo2Mat_U0_ap_start = (ap_start.read());
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_cols() {
    image_filter_AXIvideo2Mat_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_rows() {
    image_filter_AXIvideo2Mat_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Consume_1080_1920_0_U0_ap_continue() {
    image_filter_Consume_1080_1920_0_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Consume_1080_1920_0_U0_ap_start() {
    image_filter_Consume_1080_1920_0_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Consume_1080_1920_0_U0_cols() {
    image_filter_Consume_1080_1920_0_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Consume_1080_1920_0_U0_rows() {
    image_filter_Consume_1080_1920_0_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Dilate_0_0_1080_1920_U0_ap_continue() {
    image_filter_Dilate_0_0_1080_1920_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Dilate_0_0_1080_1920_U0_ap_start() {
    image_filter_Dilate_0_0_1080_1920_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Dilate_0_0_1080_1920_U0_cols() {
    image_filter_Dilate_0_0_1080_1920_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Dilate_0_0_1080_1920_U0_rows() {
    image_filter_Dilate_0_0_1080_1920_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Duplicate_U0_ap_continue() {
    image_filter_Duplicate_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Duplicate_U0_ap_start() {
    image_filter_Duplicate_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Duplicate_U0_cols() {
    image_filter_Duplicate_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Duplicate_U0_rows() {
    image_filter_Duplicate_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_FAST_t_opr_U0_ap_continue() {
    image_filter_FAST_t_opr_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_FAST_t_opr_U0_ap_start() {
    image_filter_FAST_t_opr_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_FAST_t_opr_U0_cols() {
    image_filter_FAST_t_opr_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_FAST_t_opr_U0_rows() {
    image_filter_FAST_t_opr_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_ap_continue() {
    image_filter_Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_ap_start() {
    image_filter_Mat2AXIvideo_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_cols() {
    image_filter_Mat2AXIvideo_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_U0_rows() {
    image_filter_Mat2AXIvideo_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue() {
    image_filter_PaintMask_2048_0_1080_1920_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_PaintMask_2048_0_1080_1920_U0_ap_start() {
    image_filter_PaintMask_2048_0_1080_1920_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_PaintMask_2048_0_1080_1920_U0_cols() {
    image_filter_PaintMask_2048_0_1080_1920_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_PaintMask_2048_0_1080_1920_U0_rows() {
    image_filter_PaintMask_2048_0_1080_1920_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Split_1080_1920_2048_0_U0_ap_continue() {
    image_filter_Split_1080_1920_2048_0_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Split_1080_1920_2048_0_U0_ap_start() {
    image_filter_Split_1080_1920_2048_0_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Split_1080_1920_2048_0_U0_cols() {
    image_filter_Split_1080_1920_2048_0_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Split_1080_1920_2048_0_U0_rows() {
    image_filter_Split_1080_1920_2048_0_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_video_in_TREADY() {
    video_in_TREADY = image_filter_AXIvideo2Mat_U0_video_in_TREADY.read();
}

void image_filter::thread_video_out_TDATA() {
    video_out_TDATA = image_filter_Mat2AXIvideo_U0_video_out_TDATA.read();
}

void image_filter::thread_video_out_TDEST() {
    video_out_TDEST = image_filter_Mat2AXIvideo_U0_video_out_TDEST.read();
}

void image_filter::thread_video_out_TID() {
    video_out_TID = image_filter_Mat2AXIvideo_U0_video_out_TID.read();
}

void image_filter::thread_video_out_TKEEP() {
    video_out_TKEEP = image_filter_Mat2AXIvideo_U0_video_out_TKEEP.read();
}

void image_filter::thread_video_out_TLAST() {
    video_out_TLAST = image_filter_Mat2AXIvideo_U0_video_out_TLAST.read();
}

void image_filter::thread_video_out_TSTRB() {
    video_out_TSTRB = image_filter_Mat2AXIvideo_U0_video_out_TSTRB.read();
}

void image_filter::thread_video_out_TUSER() {
    video_out_TUSER = image_filter_Mat2AXIvideo_U0_video_out_TUSER.read();
}

void image_filter::thread_video_out_TVALID() {
    video_out_TVALID = image_filter_Mat2AXIvideo_U0_video_out_TVALID.read();
}

void image_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDATA\" :  \"" << video_in_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TKEEP\" :  \"" << video_in_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TSTRB\" :  \"" << video_in_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TUSER\" :  \"" << video_in_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TLAST\" :  \"" << video_in_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TID\" :  \"" << video_in_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TDEST\" :  \"" << video_in_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDATA\" :  \"" << video_out_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TKEEP\" :  \"" << video_out_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TSTRB\" :  \"" << video_out_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TUSER\" :  \"" << video_out_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TLAST\" :  \"" << video_out_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TID\" :  \"" << video_out_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TDEST\" :  \"" << video_out_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_in_TVALID\" :  \"" << video_in_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_in_TREADY\" :  \"" << video_in_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"video_out_TVALID\" :  \"" << video_out_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"video_out_TREADY\" :  \"" << video_out_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

