// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "image_filter_Mat2AXIvideo.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_Mat2AXIvideo::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_Mat2AXIvideo::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> image_filter_Mat2AXIvideo::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> image_filter_Mat2AXIvideo::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> image_filter_Mat2AXIvideo::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> image_filter_Mat2AXIvideo::ap_ST_st5_fsm_3 = "1000";
const sc_lv<32> image_filter_Mat2AXIvideo::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_Mat2AXIvideo::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_Mat2AXIvideo::ap_const_lv32_2 = "10";
const sc_lv<1> image_filter_Mat2AXIvideo::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter_Mat2AXIvideo::ap_const_lv32_1 = "1";
const sc_lv<32> image_filter_Mat2AXIvideo::ap_const_lv32_3 = "11";
const sc_lv<11> image_filter_Mat2AXIvideo::ap_const_lv11_0 = "00000000000";
const sc_lv<2> image_filter_Mat2AXIvideo::ap_const_lv2_3 = "11";
const sc_lv<2> image_filter_Mat2AXIvideo::ap_const_lv2_0 = "00";
const sc_lv<11> image_filter_Mat2AXIvideo::ap_const_lv11_7FF = "11111111111";
const sc_lv<11> image_filter_Mat2AXIvideo::ap_const_lv11_1 = "1";

image_filter_Mat2AXIvideo::image_filter_Mat2AXIvideo(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond3_i_fu_182_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond3_i_fu_182_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_126);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_54);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_74);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_88);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_98);
    sensitive << ( img_data_stream_0_V_empty_n );
    sensitive << ( img_data_stream_1_V_empty_n );
    sensitive << ( exitcond4_i_reg_258 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_54 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_88 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_3);
    sensitive << ( ap_sig_126 );

    SC_METHOD(thread_ap_sig_ioackin_video_out_TREADY);
    sensitive << ( video_out_TREADY );
    sensitive << ( ap_reg_ioackin_video_out_TREADY );

    SC_METHOD(thread_axi_last_V_fu_204_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( p_3_i_reg_160 );
    sensitive << ( r_V_fu_171_p2 );
    sensitive << ( exitcond4_i_fu_193_p2 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );

    SC_METHOD(thread_exitcond3_i_fu_182_p2);
    sensitive << ( rows );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_i_reg_149 );

    SC_METHOD(thread_exitcond4_i_fu_193_p2);
    sensitive << ( cols );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( p_3_i_reg_160 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );

    SC_METHOD(thread_i_V_fu_187_p2);
    sensitive << ( p_i_reg_149 );

    SC_METHOD(thread_img_data_stream_0_V_blk_n);
    sensitive << ( img_data_stream_0_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );

    SC_METHOD(thread_img_data_stream_0_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );

    SC_METHOD(thread_img_data_stream_1_V_blk_n);
    sensitive << ( img_data_stream_1_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );

    SC_METHOD(thread_img_data_stream_1_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );

    SC_METHOD(thread_j_V_fu_198_p2);
    sensitive << ( p_3_i_reg_160 );

    SC_METHOD(thread_r_V_fu_171_p2);
    sensitive << ( cols );

    SC_METHOD(thread_video_out_TDATA);
    sensitive << ( img_data_stream_0_V_dout );
    sensitive << ( img_data_stream_1_V_dout );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_video_out_TDATA_blk_n);
    sensitive << ( video_out_TREADY );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );

    SC_METHOD(thread_video_out_TDEST);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_video_out_TID);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_video_out_TKEEP);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_video_out_TLAST);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );
    sensitive << ( axi_last_V_reg_267 );

    SC_METHOD(thread_video_out_TSTRB);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_video_out_TUSER);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );
    sensitive << ( tmp_user_V_fu_92 );

    SC_METHOD(thread_video_out_TVALID);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_reg_ioackin_video_out_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( exitcond4_i_reg_258 );
    sensitive << ( ap_sig_74 );
    sensitive << ( exitcond3_i_fu_182_p2 );
    sensitive << ( exitcond4_i_fu_193_p2 );
    sensitive << ( ap_sig_98 );
    sensitive << ( ap_sig_ioackin_video_out_TREADY );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ioackin_video_out_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_Mat2AXIvideo_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, img_data_stream_0_V_dout, "(port)img_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_data_stream_0_V_empty_n, "(port)img_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_data_stream_0_V_read, "(port)img_data_stream_0_V_read");
    sc_trace(mVcdFile, img_data_stream_1_V_dout, "(port)img_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_data_stream_1_V_empty_n, "(port)img_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_data_stream_1_V_read, "(port)img_data_stream_1_V_read");
    sc_trace(mVcdFile, video_out_TDATA, "(port)video_out_TDATA");
    sc_trace(mVcdFile, video_out_TVALID, "(port)video_out_TVALID");
    sc_trace(mVcdFile, video_out_TREADY, "(port)video_out_TREADY");
    sc_trace(mVcdFile, video_out_TKEEP, "(port)video_out_TKEEP");
    sc_trace(mVcdFile, video_out_TSTRB, "(port)video_out_TSTRB");
    sc_trace(mVcdFile, video_out_TUSER, "(port)video_out_TUSER");
    sc_trace(mVcdFile, video_out_TLAST, "(port)video_out_TLAST");
    sc_trace(mVcdFile, video_out_TID, "(port)video_out_TID");
    sc_trace(mVcdFile, video_out_TDEST, "(port)video_out_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, img_data_stream_0_V_blk_n, "img_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_54, "ap_sig_54");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, exitcond4_i_reg_258, "exitcond4_i_reg_258");
    sc_trace(mVcdFile, img_data_stream_1_V_blk_n, "img_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, video_out_TDATA_blk_n, "video_out_TDATA_blk_n");
    sc_trace(mVcdFile, p_3_i_reg_160, "p_3_i_reg_160");
    sc_trace(mVcdFile, ap_sig_74, "ap_sig_74");
    sc_trace(mVcdFile, r_V_fu_171_p2, "r_V_fu_171_p2");
    sc_trace(mVcdFile, exitcond3_i_fu_182_p2, "exitcond3_i_fu_182_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_88, "ap_sig_88");
    sc_trace(mVcdFile, i_V_fu_187_p2, "i_V_fu_187_p2");
    sc_trace(mVcdFile, i_V_reg_253, "i_V_reg_253");
    sc_trace(mVcdFile, exitcond4_i_fu_193_p2, "exitcond4_i_fu_193_p2");
    sc_trace(mVcdFile, ap_sig_98, "ap_sig_98");
    sc_trace(mVcdFile, ap_sig_ioackin_video_out_TREADY, "ap_sig_ioackin_video_out_TREADY");
    sc_trace(mVcdFile, j_V_fu_198_p2, "j_V_fu_198_p2");
    sc_trace(mVcdFile, axi_last_V_fu_204_p2, "axi_last_V_fu_204_p2");
    sc_trace(mVcdFile, axi_last_V_reg_267, "axi_last_V_reg_267");
    sc_trace(mVcdFile, p_i_reg_149, "p_i_reg_149");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_3, "ap_sig_cseq_ST_st5_fsm_3");
    sc_trace(mVcdFile, ap_sig_126, "ap_sig_126");
    sc_trace(mVcdFile, tmp_user_V_fu_92, "tmp_user_V_fu_92");
    sc_trace(mVcdFile, ap_reg_ioackin_video_out_TREADY, "ap_reg_ioackin_video_out_TREADY");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_Mat2AXIvideo::~image_filter_Mat2AXIvideo() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void image_filter_Mat2AXIvideo::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_video_out_TREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
              esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
              !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read()))))))) {
            ap_reg_ioackin_video_out_TREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                     esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_98.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, video_out_TREADY.read())))) {
            ap_reg_ioackin_video_out_TREADY = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
        p_3_i_reg_160 = j_V_fu_198_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read()))) {
        p_3_i_reg_160 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
         !ap_sig_74.read())) {
        p_i_reg_149 = ap_const_lv11_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
        p_i_reg_149 = i_V_reg_253.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))))) {
        tmp_user_V_fu_92 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_74.read())) {
        tmp_user_V_fu_92 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
        axi_last_V_reg_267 = axi_last_V_fu_204_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))))) {
        exitcond4_i_reg_258 = exitcond4_i_fu_193_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_253 = i_V_fu_187_p2.read();
    }
}

void image_filter_Mat2AXIvideo::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_sig_126() {
    ap_sig_126 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void image_filter_Mat2AXIvideo::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_Mat2AXIvideo::thread_ap_sig_54() {
    ap_sig_54 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void image_filter_Mat2AXIvideo::thread_ap_sig_74() {
    ap_sig_74 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_Mat2AXIvideo::thread_ap_sig_88() {
    ap_sig_88 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_Mat2AXIvideo::thread_ap_sig_98() {
    ap_sig_98 = ((esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_data_stream_0_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(img_data_stream_1_V_empty_n.read(), ap_const_logic_0)));
}

void image_filter_Mat2AXIvideo::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_54.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_88.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_sig_cseq_ST_st5_fsm_3() {
    if (ap_sig_126.read()) {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_sig_ioackin_video_out_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_video_out_TREADY.read())) {
        ap_sig_ioackin_video_out_TREADY = video_out_TREADY.read();
    } else {
        ap_sig_ioackin_video_out_TREADY = ap_const_logic_1;
    }
}

void image_filter_Mat2AXIvideo::thread_axi_last_V_fu_204_p2() {
    axi_last_V_fu_204_p2 = (!p_3_i_reg_160.read().is_01() || !r_V_fu_171_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(p_3_i_reg_160.read() == r_V_fu_171_p2.read());
}

void image_filter_Mat2AXIvideo::thread_exitcond3_i_fu_182_p2() {
    exitcond3_i_fu_182_p2 = (!p_i_reg_149.read().is_01() || !rows.read().is_01())? sc_lv<1>(): sc_lv<1>(p_i_reg_149.read() == rows.read());
}

void image_filter_Mat2AXIvideo::thread_exitcond4_i_fu_193_p2() {
    exitcond4_i_fu_193_p2 = (!p_3_i_reg_160.read().is_01() || !cols.read().is_01())? sc_lv<1>(): sc_lv<1>(p_3_i_reg_160.read() == cols.read());
}

void image_filter_Mat2AXIvideo::thread_i_V_fu_187_p2() {
    i_V_fu_187_p2 = (!p_i_reg_149.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_i_reg_149.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Mat2AXIvideo::thread_img_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0))) {
        img_data_stream_0_V_blk_n = img_data_stream_0_V_empty_n.read();
    } else {
        img_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_Mat2AXIvideo::thread_img_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))))) {
        img_data_stream_0_V_read = ap_const_logic_1;
    } else {
        img_data_stream_0_V_read = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_img_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0))) {
        img_data_stream_1_V_blk_n = img_data_stream_1_V_empty_n.read();
    } else {
        img_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_Mat2AXIvideo::thread_img_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))))) {
        img_data_stream_1_V_read = ap_const_logic_1;
    } else {
        img_data_stream_1_V_read = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_j_V_fu_198_p2() {
    j_V_fu_198_p2 = (!p_3_i_reg_160.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_3_i_reg_160.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Mat2AXIvideo::thread_r_V_fu_171_p2() {
    r_V_fu_171_p2 = (!cols.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<11>(): (sc_biguint<11>(cols.read()) + sc_bigint<11>(ap_const_lv11_7FF));
}

void image_filter_Mat2AXIvideo::thread_video_out_TDATA() {
    video_out_TDATA = esl_concat<8,8>(img_data_stream_1_V_dout.read(), img_data_stream_0_V_dout.read());
}

void image_filter_Mat2AXIvideo::thread_video_out_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0))) {
        video_out_TDATA_blk_n = video_out_TREADY.read();
    } else {
        video_out_TDATA_blk_n = ap_const_logic_1;
    }
}

void image_filter_Mat2AXIvideo::thread_video_out_TDEST() {
    video_out_TDEST = ap_const_lv1_0;
}

void image_filter_Mat2AXIvideo::thread_video_out_TID() {
    video_out_TID = ap_const_lv1_0;
}

void image_filter_Mat2AXIvideo::thread_video_out_TKEEP() {
    video_out_TKEEP = ap_const_lv2_3;
}

void image_filter_Mat2AXIvideo::thread_video_out_TLAST() {
    video_out_TLAST = axi_last_V_reg_267.read();
}

void image_filter_Mat2AXIvideo::thread_video_out_TSTRB() {
    video_out_TSTRB = ap_const_lv2_0;
}

void image_filter_Mat2AXIvideo::thread_video_out_TUSER() {
    video_out_TUSER = tmp_user_V_fu_92.read();
}

void image_filter_Mat2AXIvideo::thread_video_out_TVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_98.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_video_out_TREADY.read())))) {
        video_out_TVALID = ap_const_logic_1;
    } else {
        video_out_TVALID = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_74.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_i_fu_182_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && (ap_sig_98.read() || 
  (esl_seteq<1,1,1>(exitcond4_i_reg_258.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_video_out_TREADY.read())))) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_i_fu_193_p2.read()))) {
                ap_NS_fsm = ap_ST_st5_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

