// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "image_filter_PaintMask_2048_0_1080_1920_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_PaintMask_2048_0_1080_1920_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_PaintMask_2048_0_1080_1920_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> image_filter_PaintMask_2048_0_1080_1920_s::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> image_filter_PaintMask_2048_0_1080_1920_s::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> image_filter_PaintMask_2048_0_1080_1920_s::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> image_filter_PaintMask_2048_0_1080_1920_s::ap_ST_st6_fsm_3 = "1000";
const sc_lv<32> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv32_2 = "10";
const sc_lv<1> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv32_1 = "1";
const sc_lv<11> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv11_0 = "00000000000";
const sc_lv<32> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv32_3 = "11";
const sc_lv<11> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv11_1 = "1";
const sc_lv<8> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv8_0 = "00000000";
const sc_lv<8> image_filter_PaintMask_2048_0_1080_1920_s::ap_const_lv8_FF = "11111111";

image_filter_PaintMask_2048_0_1080_1920_s::image_filter_PaintMask_2048_0_1080_1920_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond2_i_fu_140_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond2_i_fu_140_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_109);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( p_mask_data_stream_V_empty_n );
    sensitive << ( exitcond_i_reg_201 );

    SC_METHOD(thread_ap_sig_116);
    sensitive << ( p_dst_data_stream_0_V_full_n );
    sensitive << ( p_dst_data_stream_1_V_full_n );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );

    SC_METHOD(thread_ap_sig_148);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_57);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_84);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_96);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_57 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_96 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_3);
    sensitive << ( ap_sig_148 );

    SC_METHOD(thread_exitcond2_i_fu_140_p2);
    sensitive << ( rows );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_i_reg_118 );

    SC_METHOD(thread_exitcond_i_fu_151_p2);
    sensitive << ( cols );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( p_2_i_reg_129 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_i_V_fu_145_p2);
    sensitive << ( p_i_reg_118 );

    SC_METHOD(thread_j_V_fu_156_p2);
    sensitive << ( p_2_i_reg_129 );

    SC_METHOD(thread_p_dst_data_stream_0_V_blk_n);
    sensitive << ( p_dst_data_stream_0_V_full_n );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );

    SC_METHOD(thread_p_dst_data_stream_0_V_din);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );
    sensitive << ( tmp_6_reg_210 );
    sensitive << ( tmp_i_43_reg_220 );

    SC_METHOD(thread_p_dst_data_stream_0_V_write);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_p_dst_data_stream_1_V_blk_n);
    sensitive << ( p_dst_data_stream_1_V_full_n );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );

    SC_METHOD(thread_p_dst_data_stream_1_V_din);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );
    sensitive << ( tmp_reg_215 );
    sensitive << ( tmp_i_43_reg_220 );

    SC_METHOD(thread_p_dst_data_stream_1_V_write);
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_p_mask_data_stream_V_blk_n);
    sensitive << ( p_mask_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_i_reg_201 );

    SC_METHOD(thread_p_mask_data_stream_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_i_reg_201 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_p_src_data_stream_0_V_blk_n);
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_i_reg_201 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_i_reg_201 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_p_src_data_stream_1_V_blk_n);
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond_i_reg_201 );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_i_reg_201 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_tmp_i_43_fu_162_p2);
    sensitive << ( p_mask_data_stream_V_dout );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( exitcond_i_reg_201 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_sig_84 );
    sensitive << ( exitcond2_i_fu_140_p2 );
    sensitive << ( exitcond_i_fu_151_p2 );
    sensitive << ( ap_sig_109 );
    sensitive << ( ap_sig_116 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_PaintMask_2048_0_1080_1920_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_mask_data_stream_V_dout, "(port)p_mask_data_stream_V_dout");
    sc_trace(mVcdFile, p_mask_data_stream_V_empty_n, "(port)p_mask_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_mask_data_stream_V_read, "(port)p_mask_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_din, "(port)p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_full_n, "(port)p_dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_write, "(port)p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_din, "(port)p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_full_n, "(port)p_dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_write, "(port)p_dst_data_stream_1_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_22, "ap_sig_22");
    sc_trace(mVcdFile, p_src_data_stream_0_V_blk_n, "p_src_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_57, "ap_sig_57");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, exitcond_i_reg_201, "exitcond_i_reg_201");
    sc_trace(mVcdFile, p_src_data_stream_1_V_blk_n, "p_src_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, p_mask_data_stream_V_blk_n, "p_mask_data_stream_V_blk_n");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_blk_n, "p_dst_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1, "ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_blk_n, "p_dst_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, p_2_i_reg_129, "p_2_i_reg_129");
    sc_trace(mVcdFile, ap_sig_84, "ap_sig_84");
    sc_trace(mVcdFile, exitcond2_i_fu_140_p2, "exitcond2_i_fu_140_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_96, "ap_sig_96");
    sc_trace(mVcdFile, i_V_fu_145_p2, "i_V_fu_145_p2");
    sc_trace(mVcdFile, i_V_reg_196, "i_V_reg_196");
    sc_trace(mVcdFile, exitcond_i_fu_151_p2, "exitcond_i_fu_151_p2");
    sc_trace(mVcdFile, ap_sig_109, "ap_sig_109");
    sc_trace(mVcdFile, ap_sig_116, "ap_sig_116");
    sc_trace(mVcdFile, j_V_fu_156_p2, "j_V_fu_156_p2");
    sc_trace(mVcdFile, tmp_6_reg_210, "tmp_6_reg_210");
    sc_trace(mVcdFile, tmp_reg_215, "tmp_reg_215");
    sc_trace(mVcdFile, tmp_i_43_fu_162_p2, "tmp_i_43_fu_162_p2");
    sc_trace(mVcdFile, tmp_i_43_reg_220, "tmp_i_43_reg_220");
    sc_trace(mVcdFile, p_i_reg_118, "p_i_reg_118");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_3, "ap_sig_cseq_ST_st6_fsm_3");
    sc_trace(mVcdFile, ap_sig_148, "ap_sig_148");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_PaintMask_2048_0_1080_1920_s::~image_filter_PaintMask_2048_0_1080_1920_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read()))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()))) {
        p_2_i_reg_129 = j_V_fu_156_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read()))) {
        p_2_i_reg_129 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read())) {
        p_i_reg_118 = i_V_reg_196.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_84.read())) {
        p_i_reg_118 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1 = exitcond_i_reg_201.read();
        exitcond_i_reg_201 = exitcond_i_fu_151_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_196 = i_V_fu_145_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        tmp_6_reg_210 = p_src_data_stream_0_V_dout.read();
        tmp_i_43_reg_220 = tmp_i_43_fu_162_p2.read();
        tmp_reg_215 = p_src_data_stream_1_V_dout.read();
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_109() {
    ap_sig_109 = ((esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_0_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_src_data_stream_1_V_empty_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(p_mask_data_stream_V_empty_n.read(), ap_const_logic_0)));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_116() {
    ap_sig_116 = ((esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(p_dst_data_stream_0_V_full_n.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(p_dst_data_stream_1_V_full_n.read(), ap_const_logic_0)));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_148() {
    ap_sig_148 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_22() {
    ap_sig_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_57() {
    ap_sig_57 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_84() {
    ap_sig_84 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_96() {
    ap_sig_96 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_57.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_96.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_sig_cseq_ST_st6_fsm_3() {
    if (ap_sig_148.read()) {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_exitcond2_i_fu_140_p2() {
    exitcond2_i_fu_140_p2 = (!p_i_reg_118.read().is_01() || !rows.read().is_01())? sc_lv<1>(): sc_lv<1>(p_i_reg_118.read() == rows.read());
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_exitcond_i_fu_151_p2() {
    exitcond_i_fu_151_p2 = (!p_2_i_reg_129.read().is_01() || !cols.read().is_01())? sc_lv<1>(): sc_lv<1>(p_2_i_reg_129.read() == cols.read());
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_i_V_fu_145_p2() {
    i_V_fu_145_p2 = (!p_i_reg_118.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_i_reg_118.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_j_V_fu_156_p2() {
    j_V_fu_156_p2 = (!p_2_i_reg_129.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_2_i_reg_129.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()))) {
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n.read();
    } else {
        p_dst_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_0_V_din() {
    p_dst_data_stream_0_V_din = (!tmp_i_43_reg_220.read()[0].is_01())? sc_lv<8>(): ((tmp_i_43_reg_220.read()[0].to_bool())? tmp_6_reg_210.read(): ap_const_lv8_FF);
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        p_dst_data_stream_0_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()))) {
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n.read();
    } else {
        p_dst_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_1_V_din() {
    p_dst_data_stream_1_V_din = (!tmp_i_43_reg_220.read()[0].is_01())? sc_lv<8>(): ((tmp_i_43_reg_220.read()[0].to_bool())? tmp_reg_215.read(): ap_const_lv8_0);
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_dst_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_i_reg_201_pp0_iter1.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        p_dst_data_stream_1_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_mask_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0))) {
        p_mask_data_stream_V_blk_n = p_mask_data_stream_V_empty_n.read();
    } else {
        p_mask_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_mask_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        p_mask_data_stream_V_read = ap_const_logic_1;
    } else {
        p_mask_data_stream_V_read = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_src_data_stream_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0))) {
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n.read();
    } else {
        p_src_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        p_src_data_stream_0_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_src_data_stream_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0))) {
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n.read();
    } else {
        p_src_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_201.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())))) {
        p_src_data_stream_1_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_tmp_i_43_fu_162_p2() {
    tmp_i_43_fu_162_p2 = (!p_mask_data_stream_V_dout.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(p_mask_data_stream_V_dout.read() == ap_const_lv8_0);
}

void image_filter_PaintMask_2048_0_1080_1920_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_84.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_i_fu_140_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
  !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
  ap_sig_109.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
  ap_sig_116.read())) && 
  !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i_fu_151_p2.read()) && 
  !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_st6_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

