-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_Dilate_0_0_1080_1920_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rows : IN STD_LOGIC_VECTOR (10 downto 0);
    cols : IN STD_LOGIC_VECTOR (10 downto 0);
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of image_filter_Dilate_0_0_1080_1920_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_pp0_stg0_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st13_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv12_FFE : STD_LOGIC_VECTOR (11 downto 0) := "111111111110";
    constant ap_const_lv12_FFD : STD_LOGIC_VECTOR (11 downto 0) := "111111111101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_23 : BOOLEAN;
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it5 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it6 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it7 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it8 : STD_LOGIC := '0';
    signal or_cond_i_i_i_i_reg_1008 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_958 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_i_reg_949 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal or_cond_i_i_i_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_027_0_i_i_i_reg_236 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_89 : BOOLEAN;
    signal rows_assign_cast_i_cast_fu_247_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal cols_assign_cast_i_cast_fu_251_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_24_i_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_105 : BOOLEAN;
    signal widthloop_fu_261_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_23_i_phi_fu_218_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_i_fu_266_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_271_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_2_fu_275_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_57_fu_280_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_284_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_129 : BOOLEAN;
    signal i_V_fu_298_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_944 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_38_i_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_159_not_i_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_159_not_i_reg_953 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_i_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_i_reg_963 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_2_i_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_194_2_i_reg_967 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_216_i_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_216_i_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_fu_377_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_63_reg_978 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_7_1_t_i_fu_405_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_7_1_t_i_reg_983 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_7_2_t_i_fu_432_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_7_2_t_i_reg_988 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_reg_993 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_3 : STD_LOGIC;
    signal ap_sig_158 : BOOLEAN;
    signal ap_sig_164 : BOOLEAN;
    signal ap_sig_168 : BOOLEAN;
    signal ap_reg_ppstg_exitcond_reg_993_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond_reg_993_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond_reg_993_pp0_iter3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond_reg_993_pp0_iter4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_exitcond_reg_993_pp0_iter5 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_446_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ImagLoc_x_fu_468_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_reg_1002 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_cond_i_i_i_i_fu_493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_reg_1013 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_i_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_assign_1_fu_537_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_1_reg_1024 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_3_addr_reg_1031 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_addr_reg_1037 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1043 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_buf_0_val_0_0_fu_569_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_reg_1049 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_587_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_reg_1057 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_605_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_reg_1065 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_0_fu_635_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_0_reg_1073 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_0_fu_649_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_0_reg_1080 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_0_fu_663_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_0_reg_1087 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_0_2_i_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_240_0_2_i_reg_1097 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_kernel_win_0_val_1_1_lo_reg_1102 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_1_i_reg_1108 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_1_2_i_fu_755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_240_1_2_i_reg_1119 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_kernel_win_0_val_0_1_lo_reg_1124 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_2_i_reg_1130 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_2_2_i_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_240_2_2_i_reg_1141 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal k_buf_0_val_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_i_reg_214 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_014_0_i_i_i_reg_225 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st13_fsm_4 : STD_LOGIC;
    signal ap_sig_314 : BOOLEAN;
    signal tmp_179_i_fu_542_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_kernel_win_0_val_0_1_fu_106 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_1_1_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_1_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_1_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_1_1_fu_126 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_0_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_2_0_fu_134 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_0_fu_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_58_fu_315_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_36_cast_i_cast7_fu_289_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_219_i_fu_348_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_221_i_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_362_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_61_fu_366_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_59_fu_359_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_62_fu_369_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_4_1_i_fu_383_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_221_1_i_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_64_fu_394_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_398_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_4_2_i_fu_410_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_221_2_i_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_65_fu_421_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_425_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_66_fu_452_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_39_cast_i_cast6_fu_437_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_68_fu_474_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_i_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp2_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_69_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_67_fu_509_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_assign_1_fu_519_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_fu_526_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_70_fu_533_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_22_fu_558_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_576_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_594_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_627_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_641_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_655_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_0_1_i_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_1_i_fu_719_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_240_1_1_i_fu_745_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_240_2_i_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_240_2_1_i_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_763 : BOOLEAN;
    signal ap_sig_765 : BOOLEAN;
    signal ap_sig_762 : BOOLEAN;

    component image_filter_mux_3to1_sel2_8_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component image_filter_FAST_t_opr_k_buf_val_0_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_addr_reg_1031,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_addr_reg_1037,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_4_d1);

    k_buf_0_val_5_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_addr_reg_1043,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_5_d1);

    image_filter_mux_3to1_sel2_8_1_U36 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_val_0_0_fu_130,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => col_assign_1_reg_1024,
        dout => tmp_22_fu_558_p5);

    image_filter_mux_3to1_sel2_8_1_U37 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_val_1_0_fu_138,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => col_assign_1_reg_1024,
        dout => tmp_23_fu_576_p5);

    image_filter_mux_3to1_sel2_8_1_U38 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => right_border_buf_0_val_2_0_fu_134,
        din2 => ap_const_lv8_0,
        din3 => ap_const_lv8_0,
        din4 => col_assign_1_reg_1024,
        dout => tmp_24_fu_594_p5);

    image_filter_mux_3to1_sel2_8_1_U39 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_reg_1049,
        din2 => col_buf_0_val_1_0_reg_1057,
        din3 => col_buf_0_val_2_0_reg_1065,
        din4 => tmp_63_reg_978,
        dout => tmp_25_fu_627_p5);

    image_filter_mux_3to1_sel2_8_1_U40 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_reg_1049,
        din2 => col_buf_0_val_1_0_reg_1057,
        din3 => col_buf_0_val_2_0_reg_1065,
        din4 => row_assign_7_1_t_i_reg_983,
        dout => tmp_26_fu_641_p5);

    image_filter_mux_3to1_sel2_8_1_U41 : component image_filter_mux_3to1_sel2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din1 => col_buf_0_val_0_0_reg_1049,
        din2 => col_buf_0_val_1_0_reg_1057,
        din3 => col_buf_0_val_2_0_reg_1065,
        din4 => row_assign_7_2_t_i_reg_988,
        dout => tmp_27_fu_655_p5);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = exitcond1_fu_293_p2)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = exitcond_fu_441_p2)))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_293_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = exitcond_fu_441_p2))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_293_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = exitcond_fu_441_p2))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp0_it8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then 
                    ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_293_p2))) then 
                    ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_014_0_i_i_i_reg_225_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st13_fsm_4)) then 
                p_014_0_i_i_i_reg_225 <= i_V_reg_944;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (ap_const_lv1_0 = tmp_23_i_phi_fu_218_p4))) then 
                p_014_0_i_i_i_reg_225 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    p_027_0_i_i_i_reg_236_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = exitcond_fu_441_p2))) then 
                p_027_0_i_i_i_reg_236 <= j_V_fu_446_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_293_p2))) then 
                p_027_0_i_i_i_reg_236 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    tmp_23_i_reg_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_89))) then 
                tmp_23_i_reg_214 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((ap_const_lv1_0 = tmp_23_i_phi_fu_218_p4)))) then 
                tmp_23_i_reg_214 <= tmp_24_i_fu_255_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = exitcond_fu_441_p2))) then
                ImagLoc_x_reg_1002 <= ImagLoc_x_fu_468_p2;
                brmerge_i_reg_1013 <= brmerge_i_fu_499_p2;
                or_cond_i_i_i_i_reg_1008 <= or_cond_i_i_i_i_fu_493_p2;
                or_cond_i_i_i_reg_1020 <= or_cond_i_i_i_fu_504_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then
                ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1 <= brmerge_i_reg_1013;
                ap_reg_ppstg_exitcond_reg_993_pp0_iter1 <= exitcond_reg_993;
                ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 <= or_cond_i_i_i_i_reg_1008;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1 <= or_cond_i_i_i_reg_1020;
                col_assign_1_reg_1024 <= col_assign_1_fu_537_p2;
                exitcond_reg_993 <= exitcond_fu_441_p2;
                k_buf_0_val_3_addr_reg_1031 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);
                k_buf_0_val_4_addr_reg_1037 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1043 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) then
                ap_reg_ppstg_exitcond_reg_993_pp0_iter2 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter1;
                ap_reg_ppstg_exitcond_reg_993_pp0_iter3 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter2;
                ap_reg_ppstg_exitcond_reg_993_pp0_iter4 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter3;
                ap_reg_ppstg_exitcond_reg_993_pp0_iter5 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter4;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5;
                ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6;
                ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4 <= src_kernel_win_0_val_0_0_reg_1073;
                ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4;
                ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5;
                ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6;
                ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4 <= src_kernel_win_0_val_1_0_reg_1080;
                ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4;
                col_buf_0_val_0_0_reg_1049 <= col_buf_0_val_0_0_fu_569_p3;
                col_buf_0_val_1_0_reg_1057 <= col_buf_0_val_1_0_fu_587_p3;
                col_buf_0_val_2_0_reg_1065 <= col_buf_0_val_2_0_fu_605_p3;
                src_kernel_win_0_val_0_0_reg_1073 <= src_kernel_win_0_val_0_0_fu_635_p3;
                src_kernel_win_0_val_1_0_reg_1080 <= src_kernel_win_0_val_1_0_fu_649_p3;
                src_kernel_win_0_val_2_0_reg_1087 <= src_kernel_win_0_val_2_0_fu_663_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                i_V_reg_944 <= i_V_fu_298_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and (ap_const_lv1_0 = exitcond1_fu_293_p2))) then
                icmp_reg_958 <= icmp_fu_325_p2;
                row_assign_7_1_t_i_reg_983 <= row_assign_7_1_t_i_fu_405_p2;
                row_assign_7_2_t_i_reg_988 <= row_assign_7_2_t_i_fu_432_p2;
                tmp_159_not_i_reg_953 <= tmp_159_not_i_fu_309_p2;
                tmp_194_2_i_reg_967 <= tmp_194_2_i_fu_337_p2;
                tmp_194_i_reg_963 <= tmp_194_i_fu_331_p2;
                tmp_216_i_reg_971 <= tmp_216_i_fu_343_p2;
                tmp_38_i_reg_949 <= tmp_38_i_fu_304_p2;
                tmp_63_reg_978 <= tmp_63_fu_377_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then
                right_border_buf_0_val_0_0_fu_130 <= col_buf_0_val_0_0_fu_569_p3;
                right_border_buf_0_val_1_0_fu_138 <= col_buf_0_val_1_0_fu_587_p3;
                right_border_buf_0_val_2_0_fu_134 <= col_buf_0_val_2_0_fu_605_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it6) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_993_pp0_iter5))) then
                src_kernel_win_0_val_0_1_1_fu_110 <= src_kernel_win_0_val_0_1_fu_106;
                src_kernel_win_0_val_0_1_fu_106 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5)))) then
                src_kernel_win_0_val_0_1_lo_reg_1124 <= src_kernel_win_0_val_0_1_fu_106;
                temp_0_i_i_i_059_i_i_1_2_i_reg_1130 <= temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_993_pp0_iter3))) then
                src_kernel_win_0_val_1_1_1_fu_118 <= src_kernel_win_0_val_1_1_fu_114;
                src_kernel_win_0_val_1_1_fu_114 <= src_kernel_win_0_val_1_0_reg_1080;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3)))) then
                src_kernel_win_0_val_1_1_lo_reg_1102 <= src_kernel_win_0_val_1_1_fu_114;
                temp_0_i_i_i_059_i_i_1_1_i_reg_1108 <= temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and (ap_const_lv1_0 = ap_reg_ppstg_exitcond_reg_993_pp0_iter2))) then
                src_kernel_win_0_val_2_1_1_fu_126 <= src_kernel_win_0_val_2_1_fu_122;
                src_kernel_win_0_val_2_1_fu_122 <= src_kernel_win_0_val_2_0_fu_663_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2)))) then
                temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092 <= temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3;
                tmp_240_0_2_i_reg_1097 <= tmp_240_0_2_i_fu_689_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4)))) then
                temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114 <= temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3;
                tmp_240_1_2_i_reg_1119 <= tmp_240_1_2_i_fu_755_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6)))) then
                temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136 <= temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3;
                tmp_240_2_2_i_reg_1141 <= tmp_240_2_2_i_fu_807_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it0, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it7, ap_reg_ppiten_pp0_it8, ap_sig_89, tmp_23_i_phi_fu_218_p4, exitcond1_fu_293_p2, exitcond_fu_441_p2, ap_sig_164, ap_sig_168)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_89)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((ap_const_lv1_0 = tmp_23_i_phi_fu_218_p4)) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st3_fsm_2 => 
                if (not((ap_const_lv1_0 = exitcond1_fu_293_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                end if;
            when ap_ST_pp0_stg0_fsm_3 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = exitcond_fu_441_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                elsif ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it7))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = exitcond_fu_441_p2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                    ap_NS_fsm <= ap_ST_st13_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                end if;
            when ap_ST_st13_fsm_4 => 
                ap_NS_fsm <= ap_ST_st3_fsm_2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ImagLoc_x_fu_468_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(tmp_39_cast_i_cast6_fu_437_p1));

    ap_done_assign_proc : process(ap_done_reg, exitcond1_fu_293_p2, ap_sig_cseq_ST_st3_fsm_2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = exitcond1_fu_293_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond1_fu_293_p2, ap_sig_cseq_ST_st3_fsm_2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2) and not((ap_const_lv1_0 = exitcond1_fu_293_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_105_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_105 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_129_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_129 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_158_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_158 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_164_assign_proc : process(p_src_data_stream_V_empty_n, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949)
    begin
                ap_sig_164 <= ((not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and (p_src_data_stream_V_empty_n = ap_const_logic_0)) or (not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and (p_src_data_stream_V_empty_n = ap_const_logic_0)));
    end process;


    ap_sig_168_assign_proc : process(p_dst_data_stream_V_full_n, ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7)
    begin
                ap_sig_168 <= (not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7)) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;


    ap_sig_23_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_23 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_314_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_314 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_762_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1)
    begin
                ap_sig_762 <= ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)));
    end process;


    ap_sig_763_assign_proc : process(icmp_reg_958, tmp_194_i_reg_963)
    begin
                ap_sig_763 <= ((ap_const_lv1_0 = icmp_reg_958) and not((ap_const_lv1_0 = tmp_194_i_reg_963)));
    end process;


    ap_sig_765_assign_proc : process(icmp_reg_958, tmp_38_i_reg_949)
    begin
                ap_sig_765 <= (not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)));
    end process;


    ap_sig_89_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_89 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_sig_cseq_ST_pp0_stg0_fsm_3_assign_proc : process(ap_sig_158)
    begin
        if (ap_sig_158) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st13_fsm_4_assign_proc : process(ap_sig_314)
    begin
        if (ap_sig_314) then 
            ap_sig_cseq_ST_st13_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st13_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_23)
    begin
        if (ap_sig_23) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_105)
    begin
        if (ap_sig_105) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_129)
    begin
        if (ap_sig_129) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_i_fu_499_p2 <= (tmp_43_i_fu_488_p2 or tmp_159_not_i_reg_953);
    col_assign_1_fu_537_p2 <= std_logic_vector(unsigned(tmp_fu_271_p1) - unsigned(tmp_70_fu_533_p1));
    col_buf_0_val_0_0_fu_569_p3 <= 
        k_buf_0_val_3_q0 when (ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1(0) = '1') else 
        tmp_22_fu_558_p5;
    col_buf_0_val_1_0_fu_587_p3 <= 
        k_buf_0_val_4_q0 when (ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1(0) = '1') else 
        tmp_23_fu_576_p5;
    col_buf_0_val_2_0_fu_605_p3 <= 
        k_buf_0_val_5_q0 when (ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1(0) = '1') else 
        tmp_24_fu_594_p5;
    cols_assign_cast_i_cast_fu_251_p1 <= std_logic_vector(resize(unsigned(cols),12));
    exitcond1_fu_293_p2 <= "1" when (p_014_0_i_i_i_reg_225 = tmp_s_fu_284_p2) else "0";
    exitcond_fu_441_p2 <= "1" when (p_027_0_i_i_i_reg_236 = widthloop_fu_261_p2) else "0";
    i_V_fu_298_p2 <= std_logic_vector(unsigned(p_014_0_i_i_i_reg_225) + unsigned(ap_const_lv11_1));
    icmp2_fu_462_p2 <= "0" when (tmp_66_fu_452_p4 = ap_const_lv10_0) else "1";
    icmp_fu_325_p2 <= "0" when (tmp_58_fu_315_p4 = ap_const_lv10_0) else "1";
    j_V_fu_446_p2 <= std_logic_vector(unsigned(p_027_0_i_i_i_reg_236) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);

    k_buf_0_val_3_ce0_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it8, ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_sig_164, ap_sig_168)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_2_i_reg_967, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_2_i_reg_967))))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_2_i_reg_967, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_2_i_reg_967))))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);

    k_buf_0_val_4_ce0_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it8, ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_sig_164, ap_sig_168)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_i_reg_963, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_i_reg_963))))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_d1_assign_proc : process(p_src_data_stream_V_dout, k_buf_0_val_3_q0, ap_sig_763, ap_sig_765, ap_sig_762)
    begin
        if (ap_sig_762) then
            if (ap_sig_765) then 
                k_buf_0_val_4_d1 <= k_buf_0_val_3_q0;
            elsif (ap_sig_763) then 
                k_buf_0_val_4_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_4_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_i_reg_963, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_i_reg_963))))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= tmp_179_i_fu_542_p1(11 - 1 downto 0);

    k_buf_0_val_5_ce0_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it1, ap_reg_ppiten_pp0_it8, ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_sig_164, ap_sig_168)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_i_reg_963, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_i_reg_963))))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_d1_assign_proc : process(p_src_data_stream_V_dout, k_buf_0_val_4_q0, ap_sig_763, ap_sig_765, ap_sig_762)
    begin
        if (ap_sig_762) then
            if (ap_sig_765) then 
                k_buf_0_val_5_d1 <= k_buf_0_val_4_q0;
            elsif (ap_sig_763) then 
                k_buf_0_val_5_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_5_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, tmp_194_i_reg_963, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))) and not((ap_const_lv1_0 = tmp_194_i_reg_963))))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    or_cond_i_i_i_fu_504_p2 <= (icmp_reg_958 and icmp2_fu_462_p2);
    or_cond_i_i_i_i_fu_493_p2 <= (tmp_43_i_fu_488_p2 and rev_fu_482_p2);
    p_assign_1_fu_519_p3 <= 
        ap_const_lv11_0 when (tmp_69_fu_512_p3(0) = '1') else 
        tmp_35_i_fu_266_p2;
    p_assign_2_fu_275_p2 <= std_logic_vector(signed(ap_const_lv11_7FF) + signed(rows));
    p_assign_4_1_i_fu_383_p2 <= std_logic_vector(unsigned(tmp_36_cast_i_cast7_fu_289_p1) + unsigned(ap_const_lv12_FFE));
    p_assign_4_2_i_fu_410_p2 <= std_logic_vector(unsigned(tmp_36_cast_i_cast7_fu_289_p1) + unsigned(ap_const_lv12_FFD));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7)))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7 when (tmp_240_2_2_i_reg_1141(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136;

    p_dst_data_stream_V_write_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7, ap_sig_164, ap_sig_168)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168))))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_reg_ppiten_pp0_it2, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958)) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949))))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it8, ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1, icmp_reg_958, tmp_38_i_reg_949, ap_sig_164, ap_sig_168)
    begin
        if ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and (ap_const_lv1_0 = icmp_reg_958) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not((ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 = ap_const_lv1_0)) and not((ap_const_lv1_0 = icmp_reg_958)) and not((ap_const_lv1_0 = tmp_38_i_reg_949)) and not((((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and ap_sig_164) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it8) and ap_sig_168)))))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    rev_fu_482_p2 <= (tmp_68_fu_474_p3 xor ap_const_lv1_1);
    row_assign_7_1_t_i_fu_405_p2 <= std_logic_vector(unsigned(tmp_57_fu_280_p1) - unsigned(tmp_20_fu_398_p3));
    row_assign_7_2_t_i_fu_432_p2 <= std_logic_vector(unsigned(tmp_57_fu_280_p1) - unsigned(tmp_21_fu_425_p3));
    rows_assign_cast_i_cast_fu_247_p1 <= std_logic_vector(resize(unsigned(rows),12));
    src_kernel_win_0_val_0_0_fu_635_p3 <= 
        tmp_25_fu_627_p5 when (tmp_216_i_reg_971(0) = '1') else 
        col_buf_0_val_0_0_reg_1049;
    src_kernel_win_0_val_1_0_fu_649_p3 <= 
        tmp_26_fu_641_p5 when (tmp_216_i_reg_971(0) = '1') else 
        col_buf_0_val_1_0_reg_1057;
    src_kernel_win_0_val_2_0_fu_663_p3 <= 
        tmp_27_fu_655_p5 when (tmp_216_i_reg_971(0) = '1') else 
        col_buf_0_val_2_0_reg_1065;
    temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3 <= 
        src_kernel_win_0_val_2_1_fu_122 when (tmp_240_0_1_i_fu_675_p2(0) = '1') else 
        src_kernel_win_0_val_2_1_1_fu_126;
    temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3 <= 
        src_kernel_win_0_val_2_0_reg_1087 when (tmp_240_0_2_i_reg_1097(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092;
    temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3 <= 
        src_kernel_win_0_val_1_1_lo_reg_1102 when (tmp_240_1_1_i_fu_745_p2(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_1_i_reg_1108;
    temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3 <= 
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5 when (tmp_240_1_2_i_reg_1119(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114;
    temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3 <= 
        src_kernel_win_0_val_1_1_1_fu_118 when (tmp_240_1_i_fu_719_p2(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3;
    temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3 <= 
        src_kernel_win_0_val_0_1_lo_reg_1124 when (tmp_240_2_1_i_fu_797_p2(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_2_i_reg_1130;
    temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3 <= 
        src_kernel_win_0_val_0_1_1_fu_110 when (tmp_240_2_i_fu_771_p2(0) = '1') else 
        temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3;
    tmp_159_not_i_fu_309_p2 <= (tmp_38_i_fu_304_p2 xor ap_const_lv1_1);
    tmp_179_i_fu_542_p1 <= std_logic_vector(resize(unsigned(x_fu_526_p3),64));
    tmp_194_2_i_fu_337_p2 <= "1" when (p_014_0_i_i_i_reg_225 = ap_const_lv11_1) else "0";
    tmp_194_i_fu_331_p2 <= "1" when (p_014_0_i_i_i_reg_225 = ap_const_lv11_0) else "0";
    tmp_20_fu_398_p3 <= 
        tmp_64_fu_394_p1 when (tmp_221_1_i_fu_389_p2(0) = '1') else 
        tmp_57_fu_280_p1;
    tmp_216_i_fu_343_p2 <= "1" when (unsigned(p_014_0_i_i_i_reg_225) > unsigned(rows)) else "0";
    tmp_219_i_fu_348_p2 <= std_logic_vector(unsigned(tmp_36_cast_i_cast7_fu_289_p1) + unsigned(ap_const_lv12_FFF));
    tmp_21_fu_425_p3 <= 
        tmp_65_fu_421_p1 when (tmp_221_2_i_fu_416_p2(0) = '1') else 
        tmp_57_fu_280_p1;
    tmp_221_1_i_fu_389_p2 <= "1" when (signed(p_assign_4_1_i_fu_383_p2) < signed(rows_assign_cast_i_cast_fu_247_p1)) else "0";
    tmp_221_2_i_fu_416_p2 <= "1" when (signed(p_assign_4_2_i_fu_410_p2) < signed(rows_assign_cast_i_cast_fu_247_p1)) else "0";
    tmp_221_i_fu_354_p2 <= "1" when (signed(tmp_219_i_fu_348_p2) < signed(rows_assign_cast_i_cast_fu_247_p1)) else "0";
    tmp_23_i_phi_fu_218_p4 <= tmp_23_i_reg_214;
    tmp_240_0_1_i_fu_675_p2 <= "1" when (unsigned(src_kernel_win_0_val_2_1_fu_122) > unsigned(src_kernel_win_0_val_2_1_1_fu_126)) else "0";
    tmp_240_0_2_i_fu_689_p2 <= "1" when (unsigned(src_kernel_win_0_val_2_0_fu_663_p3) > unsigned(temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3)) else "0";
    tmp_240_1_1_i_fu_745_p2 <= "1" when (unsigned(src_kernel_win_0_val_1_1_lo_reg_1102) > unsigned(temp_0_i_i_i_059_i_i_1_1_i_reg_1108)) else "0";
    tmp_240_1_2_i_fu_755_p2 <= "1" when (unsigned(ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4) > unsigned(temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3)) else "0";
    tmp_240_1_i_fu_719_p2 <= "1" when (unsigned(src_kernel_win_0_val_1_1_1_fu_118) > unsigned(temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3)) else "0";
    tmp_240_2_1_i_fu_797_p2 <= "1" when (unsigned(src_kernel_win_0_val_0_1_lo_reg_1124) > unsigned(temp_0_i_i_i_059_i_i_1_2_i_reg_1130)) else "0";
    tmp_240_2_2_i_fu_807_p2 <= "1" when (unsigned(ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6) > unsigned(temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3)) else "0";
    tmp_240_2_i_fu_771_p2 <= "1" when (unsigned(src_kernel_win_0_val_0_1_1_fu_110) > unsigned(temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3)) else "0";
    tmp_24_i_fu_255_p2 <= (tmp_23_i_reg_214 xor ap_const_lv1_1);
    tmp_35_i_fu_266_p2 <= std_logic_vector(signed(ap_const_lv11_7FF) + signed(cols));
    tmp_36_cast_i_cast7_fu_289_p1 <= std_logic_vector(resize(unsigned(p_014_0_i_i_i_reg_225),12));
    tmp_38_i_fu_304_p2 <= "1" when (unsigned(p_014_0_i_i_i_reg_225) < unsigned(rows)) else "0";
    tmp_39_cast_i_cast6_fu_437_p1 <= std_logic_vector(resize(unsigned(p_027_0_i_i_i_reg_236),12));
    tmp_43_i_fu_488_p2 <= "1" when (signed(ImagLoc_x_fu_468_p2) < signed(cols_assign_cast_i_cast_fu_251_p1)) else "0";
    tmp_57_fu_280_p1 <= p_assign_2_fu_275_p2(2 - 1 downto 0);
    tmp_58_fu_315_p4 <= p_014_0_i_i_i_reg_225(10 downto 1);
    tmp_59_fu_359_p1 <= p_assign_2_fu_275_p2(2 - 1 downto 0);
    tmp_60_fu_362_p1 <= tmp_219_i_fu_348_p2(2 - 1 downto 0);
    tmp_61_fu_366_p1 <= p_assign_2_fu_275_p2(2 - 1 downto 0);
    tmp_62_fu_369_p3 <= 
        tmp_60_fu_362_p1 when (tmp_221_i_fu_354_p2(0) = '1') else 
        tmp_61_fu_366_p1;
    tmp_63_fu_377_p2 <= std_logic_vector(unsigned(tmp_59_fu_359_p1) - unsigned(tmp_62_fu_369_p3));
    tmp_64_fu_394_p1 <= p_assign_4_1_i_fu_383_p2(2 - 1 downto 0);
    tmp_65_fu_421_p1 <= p_assign_4_2_i_fu_410_p2(2 - 1 downto 0);
    tmp_66_fu_452_p4 <= p_027_0_i_i_i_reg_236(10 downto 1);
    tmp_67_fu_509_p1 <= ImagLoc_x_reg_1002(11 - 1 downto 0);
    tmp_68_fu_474_p3 <= ImagLoc_x_fu_468_p2(11 downto 11);
    tmp_69_fu_512_p3 <= ImagLoc_x_reg_1002(11 downto 11);
    tmp_70_fu_533_p1 <= x_fu_526_p3(2 - 1 downto 0);
    tmp_fu_271_p1 <= tmp_35_i_fu_266_p2(2 - 1 downto 0);
    tmp_s_fu_284_p2 <= std_logic_vector(unsigned(ap_const_lv11_2) + unsigned(rows));
    widthloop_fu_261_p2 <= std_logic_vector(unsigned(ap_const_lv11_2) + unsigned(cols));
    x_fu_526_p3 <= 
        tmp_67_fu_509_p1 when (or_cond_i_i_i_i_reg_1008(0) = '1') else 
        p_assign_1_fu_519_p3;
end behav;
