#pragma line 1 "simple_image_process/src/simple.c" ::: 0
#pragma line 1 "simple_image_process/src/simple.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "simple_image_process/src/simple.c" 2 ::: 194
#pragma line 1 "simple_image_process/src/../include/simple.h" 1 ::: 241
#pragma line 47 "simple_image_process/src/simple.c" 2 ::: 300
