#pragma line 1 "simple_image_process/src/simple.c" ::: -10
#pragma line 1 "simple_image_process/src/simple.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "simple_image_process/src/simple.c" 2 ::: 184
#pragma line 1 "simple_image_process/src/../include/simple.h" 1 ::: 231
#pragma line 47 "simple_image_process/src/simple.c" 2 ::: 290
