// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_Dilate_0_0_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        rows,
        cols,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st13_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv12_FFE = 12'b111111111110;
parameter    ap_const_lv12_FFD = 12'b111111111101;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv8_0 = 8'b00000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [10:0] rows;
input  [10:0] cols;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_23;
reg    p_src_data_stream_V_blk_n;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg    ap_reg_ppiten_pp0_it6;
reg    ap_reg_ppiten_pp0_it7;
reg    ap_reg_ppiten_pp0_it8;
reg   [0:0] or_cond_i_i_i_i_reg_1008;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1;
reg   [0:0] icmp_reg_958;
reg   [0:0] tmp_38_i_reg_949;
reg    p_dst_data_stream_V_blk_n;
reg   [0:0] or_cond_i_i_i_reg_1020;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7;
reg   [10:0] p_027_0_i_i_i_reg_236;
reg    ap_sig_89;
wire   [11:0] rows_assign_cast_i_cast_fu_247_p1;
wire   [11:0] cols_assign_cast_i_cast_fu_251_p1;
wire   [0:0] tmp_24_i_fu_255_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_105;
wire   [10:0] widthloop_fu_261_p2;
wire   [0:0] tmp_23_i_phi_fu_218_p4;
wire   [10:0] tmp_35_i_fu_266_p2;
wire   [1:0] tmp_fu_271_p1;
wire   [10:0] p_assign_2_fu_275_p2;
wire   [1:0] tmp_57_fu_280_p1;
wire   [10:0] tmp_s_fu_284_p2;
wire   [0:0] exitcond1_fu_293_p2;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_129;
wire   [10:0] i_V_fu_298_p2;
reg   [10:0] i_V_reg_944;
wire   [0:0] tmp_38_i_fu_304_p2;
wire   [0:0] tmp_159_not_i_fu_309_p2;
reg   [0:0] tmp_159_not_i_reg_953;
wire   [0:0] icmp_fu_325_p2;
wire   [0:0] tmp_194_i_fu_331_p2;
reg   [0:0] tmp_194_i_reg_963;
wire   [0:0] tmp_194_2_i_fu_337_p2;
reg   [0:0] tmp_194_2_i_reg_967;
wire   [0:0] tmp_216_i_fu_343_p2;
reg   [0:0] tmp_216_i_reg_971;
wire   [1:0] tmp_63_fu_377_p2;
reg   [1:0] tmp_63_reg_978;
wire   [1:0] row_assign_7_1_t_i_fu_405_p2;
reg   [1:0] row_assign_7_1_t_i_reg_983;
wire   [1:0] row_assign_7_2_t_i_fu_432_p2;
reg   [1:0] row_assign_7_2_t_i_reg_988;
wire   [0:0] exitcond_fu_441_p2;
reg   [0:0] exitcond_reg_993;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_158;
reg    ap_sig_164;
reg    ap_sig_168;
reg   [0:0] ap_reg_ppstg_exitcond_reg_993_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_reg_993_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond_reg_993_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond_reg_993_pp0_iter4;
reg   [0:0] ap_reg_ppstg_exitcond_reg_993_pp0_iter5;
wire   [10:0] j_V_fu_446_p2;
wire   [11:0] ImagLoc_x_fu_468_p2;
reg   [11:0] ImagLoc_x_reg_1002;
wire   [0:0] or_cond_i_i_i_i_fu_493_p2;
wire   [0:0] brmerge_i_fu_499_p2;
reg   [0:0] brmerge_i_reg_1013;
reg   [0:0] ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1;
wire   [0:0] or_cond_i_i_i_fu_504_p2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5;
reg   [0:0] ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6;
wire   [1:0] col_assign_1_fu_537_p2;
reg   [1:0] col_assign_1_reg_1024;
reg   [10:0] k_buf_0_val_3_addr_reg_1031;
reg   [10:0] k_buf_0_val_4_addr_reg_1037;
reg   [10:0] k_buf_0_val_5_addr_reg_1043;
wire   [7:0] col_buf_0_val_0_0_fu_569_p3;
reg   [7:0] col_buf_0_val_0_0_reg_1049;
wire   [7:0] col_buf_0_val_1_0_fu_587_p3;
reg   [7:0] col_buf_0_val_1_0_reg_1057;
wire   [7:0] col_buf_0_val_2_0_fu_605_p3;
reg   [7:0] col_buf_0_val_2_0_reg_1065;
wire   [7:0] src_kernel_win_0_val_0_0_fu_635_p3;
reg   [7:0] src_kernel_win_0_val_0_0_reg_1073;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7;
wire   [7:0] src_kernel_win_0_val_1_0_fu_649_p3;
reg   [7:0] src_kernel_win_0_val_1_0_reg_1080;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5;
wire   [7:0] src_kernel_win_0_val_2_0_fu_663_p3;
reg   [7:0] src_kernel_win_0_val_2_0_reg_1087;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092;
wire   [0:0] tmp_240_0_2_i_fu_689_p2;
reg   [0:0] tmp_240_0_2_i_reg_1097;
reg   [7:0] src_kernel_win_0_val_1_1_lo_reg_1102;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_1_i_reg_1108;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114;
wire   [0:0] tmp_240_1_2_i_fu_755_p2;
reg   [0:0] tmp_240_1_2_i_reg_1119;
reg   [7:0] src_kernel_win_0_val_0_1_lo_reg_1124;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_2_i_reg_1130;
wire   [7:0] temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3;
reg   [7:0] temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136;
wire   [0:0] tmp_240_2_2_i_fu_807_p2;
reg   [0:0] tmp_240_2_2_i_reg_1141;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [0:0] tmp_23_i_reg_214;
reg   [10:0] p_014_0_i_i_i_reg_225;
reg    ap_sig_cseq_ST_st13_fsm_4;
reg    ap_sig_314;
wire   [63:0] tmp_179_i_fu_542_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_106;
reg   [7:0] src_kernel_win_0_val_0_1_1_fu_110;
reg   [7:0] src_kernel_win_0_val_1_1_fu_114;
reg   [7:0] src_kernel_win_0_val_1_1_1_fu_118;
reg   [7:0] src_kernel_win_0_val_2_1_fu_122;
reg   [7:0] src_kernel_win_0_val_2_1_1_fu_126;
reg   [7:0] right_border_buf_0_val_0_0_fu_130;
reg   [7:0] right_border_buf_0_val_2_0_fu_134;
reg   [7:0] right_border_buf_0_val_1_0_fu_138;
wire   [9:0] tmp_58_fu_315_p4;
wire   [11:0] tmp_36_cast_i_cast7_fu_289_p1;
wire   [11:0] tmp_219_i_fu_348_p2;
wire   [0:0] tmp_221_i_fu_354_p2;
wire   [1:0] tmp_60_fu_362_p1;
wire   [1:0] tmp_61_fu_366_p1;
wire   [1:0] tmp_59_fu_359_p1;
wire   [1:0] tmp_62_fu_369_p3;
wire   [11:0] p_assign_4_1_i_fu_383_p2;
wire   [0:0] tmp_221_1_i_fu_389_p2;
wire   [1:0] tmp_64_fu_394_p1;
wire   [1:0] tmp_20_fu_398_p3;
wire   [11:0] p_assign_4_2_i_fu_410_p2;
wire   [0:0] tmp_221_2_i_fu_416_p2;
wire   [1:0] tmp_65_fu_421_p1;
wire   [1:0] tmp_21_fu_425_p3;
wire   [9:0] tmp_66_fu_452_p4;
wire   [11:0] tmp_39_cast_i_cast6_fu_437_p1;
wire   [0:0] tmp_68_fu_474_p3;
wire   [0:0] tmp_43_i_fu_488_p2;
wire   [0:0] rev_fu_482_p2;
wire   [0:0] icmp2_fu_462_p2;
wire   [0:0] tmp_69_fu_512_p3;
wire   [10:0] tmp_67_fu_509_p1;
wire   [10:0] p_assign_1_fu_519_p3;
wire   [10:0] x_fu_526_p3;
wire   [1:0] tmp_70_fu_533_p1;
wire   [7:0] tmp_22_fu_558_p5;
wire   [7:0] tmp_23_fu_576_p5;
wire   [7:0] tmp_24_fu_594_p5;
wire   [7:0] tmp_25_fu_627_p5;
wire   [7:0] tmp_26_fu_641_p5;
wire   [7:0] tmp_27_fu_655_p5;
wire   [0:0] tmp_240_0_1_i_fu_675_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3;
wire   [0:0] tmp_240_1_i_fu_719_p2;
wire   [0:0] tmp_240_1_1_i_fu_745_p2;
wire   [7:0] temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3;
wire   [0:0] tmp_240_2_i_fu_771_p2;
wire   [0:0] tmp_240_2_1_i_fu_797_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_sig_763;
reg    ap_sig_765;
reg    ap_sig_762;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'b1;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
#0 ap_reg_ppiten_pp0_it6 = 1'b0;
#0 ap_reg_ppiten_pp0_it7 = 1'b0;
#0 ap_reg_ppiten_pp0_it8 = 1'b0;
end

image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_1031),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_1037),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_1043),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U36(
    .din1(right_border_buf_0_val_0_0_fu_130),
    .din2(ap_const_lv8_0),
    .din3(ap_const_lv8_0),
    .din4(col_assign_1_reg_1024),
    .dout(tmp_22_fu_558_p5)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U37(
    .din1(right_border_buf_0_val_1_0_fu_138),
    .din2(ap_const_lv8_0),
    .din3(ap_const_lv8_0),
    .din4(col_assign_1_reg_1024),
    .dout(tmp_23_fu_576_p5)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U38(
    .din1(right_border_buf_0_val_2_0_fu_134),
    .din2(ap_const_lv8_0),
    .din3(ap_const_lv8_0),
    .din4(col_assign_1_reg_1024),
    .dout(tmp_24_fu_594_p5)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U39(
    .din1(col_buf_0_val_0_0_reg_1049),
    .din2(col_buf_0_val_1_0_reg_1057),
    .din3(col_buf_0_val_2_0_reg_1065),
    .din4(tmp_63_reg_978),
    .dout(tmp_25_fu_627_p5)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U40(
    .din1(col_buf_0_val_0_0_reg_1049),
    .din2(col_buf_0_val_1_0_reg_1057),
    .din3(col_buf_0_val_2_0_reg_1065),
    .din4(row_assign_7_1_t_i_reg_983),
    .dout(tmp_26_fu_641_p5)
);

image_filter_mux_3to1_sel2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
image_filter_mux_3to1_sel2_8_1_U41(
    .din1(col_buf_0_val_0_0_reg_1049),
    .din2(col_buf_0_val_1_0_reg_1057),
    .din3(col_buf_0_val_2_0_reg_1065),
    .din4(row_assign_7_2_t_i_reg_988),
    .dout(tmp_27_fu_655_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_293_p2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == exitcond_fu_441_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_293_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == exitcond_fu_441_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_293_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == exitcond_fu_441_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= 1'b0;
    end else begin
        if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_293_p2))) begin
            ap_reg_ppiten_pp0_it8 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st13_fsm_4)) begin
        p_014_0_i_i_i_reg_225 <= i_V_reg_944;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == tmp_23_i_phi_fu_218_p4))) begin
        p_014_0_i_i_i_reg_225 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == exitcond_fu_441_p2))) begin
        p_027_0_i_i_i_reg_236 <= j_V_fu_446_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_293_p2))) begin
        p_027_0_i_i_i_reg_236 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_89)) begin
        tmp_23_i_reg_214 <= 1'b0;
    end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == tmp_23_i_phi_fu_218_p4))) begin
        tmp_23_i_reg_214 <= tmp_24_i_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == exitcond_fu_441_p2))) begin
        ImagLoc_x_reg_1002 <= ImagLoc_x_fu_468_p2;
        brmerge_i_reg_1013 <= brmerge_i_fu_499_p2;
        or_cond_i_i_i_i_reg_1008 <= or_cond_i_i_i_i_fu_493_p2;
        or_cond_i_i_i_reg_1020 <= or_cond_i_i_i_fu_504_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1 <= brmerge_i_reg_1013;
        ap_reg_ppstg_exitcond_reg_993_pp0_iter1 <= exitcond_reg_993;
        ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 <= or_cond_i_i_i_i_reg_1008;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1 <= or_cond_i_i_i_reg_1020;
        col_assign_1_reg_1024 <= col_assign_1_fu_537_p2;
        exitcond_reg_993 <= exitcond_fu_441_p2;
        k_buf_0_val_3_addr_reg_1031 <= tmp_179_i_fu_542_p1;
        k_buf_0_val_4_addr_reg_1037 <= tmp_179_i_fu_542_p1;
        k_buf_0_val_5_addr_reg_1043 <= tmp_179_i_fu_542_p1;
    end
end

always @ (posedge ap_clk) begin
    if (~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) begin
        ap_reg_ppstg_exitcond_reg_993_pp0_iter2 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter1;
        ap_reg_ppstg_exitcond_reg_993_pp0_iter3 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter2;
        ap_reg_ppstg_exitcond_reg_993_pp0_iter4 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter3;
        ap_reg_ppstg_exitcond_reg_993_pp0_iter5 <= ap_reg_ppstg_exitcond_reg_993_pp0_iter4;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter1;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5;
        ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7 <= ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4 <= src_kernel_win_0_val_0_0_reg_1073;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter4;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5;
        ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4 <= src_kernel_win_0_val_1_0_reg_1080;
        ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5 <= ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4;
        col_buf_0_val_0_0_reg_1049 <= col_buf_0_val_0_0_fu_569_p3;
        col_buf_0_val_1_0_reg_1057 <= col_buf_0_val_1_0_fu_587_p3;
        col_buf_0_val_2_0_reg_1065 <= col_buf_0_val_2_0_fu_605_p3;
        src_kernel_win_0_val_0_0_reg_1073 <= src_kernel_win_0_val_0_0_fu_635_p3;
        src_kernel_win_0_val_1_0_reg_1080 <= src_kernel_win_0_val_1_0_fu_649_p3;
        src_kernel_win_0_val_2_0_reg_1087 <= src_kernel_win_0_val_2_0_fu_663_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_V_reg_944 <= i_V_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & (1'b0 == exitcond1_fu_293_p2))) begin
        icmp_reg_958 <= icmp_fu_325_p2;
        row_assign_7_1_t_i_reg_983 <= row_assign_7_1_t_i_fu_405_p2;
        row_assign_7_2_t_i_reg_988 <= row_assign_7_2_t_i_fu_432_p2;
        tmp_159_not_i_reg_953 <= tmp_159_not_i_fu_309_p2;
        tmp_194_2_i_reg_967 <= tmp_194_2_i_fu_337_p2;
        tmp_194_i_reg_963 <= tmp_194_i_fu_331_p2;
        tmp_216_i_reg_971 <= tmp_216_i_fu_343_p2;
        tmp_38_i_reg_949 <= tmp_38_i_fu_304_p2;
        tmp_63_reg_978 <= tmp_63_fu_377_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        right_border_buf_0_val_0_0_fu_130 <= col_buf_0_val_0_0_fu_569_p3;
        right_border_buf_0_val_1_0_fu_138 <= col_buf_0_val_1_0_fu_587_p3;
        right_border_buf_0_val_2_0_fu_134 <= col_buf_0_val_2_0_fu_605_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it6) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == ap_reg_ppstg_exitcond_reg_993_pp0_iter5))) begin
        src_kernel_win_0_val_0_1_1_fu_110 <= src_kernel_win_0_val_0_1_fu_106;
        src_kernel_win_0_val_0_1_fu_106 <= ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter5;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter5))) begin
        src_kernel_win_0_val_0_1_lo_reg_1124 <= src_kernel_win_0_val_0_1_fu_106;
        temp_0_i_i_i_059_i_i_1_2_i_reg_1130 <= temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it4) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == ap_reg_ppstg_exitcond_reg_993_pp0_iter3))) begin
        src_kernel_win_0_val_1_1_1_fu_118 <= src_kernel_win_0_val_1_1_fu_114;
        src_kernel_win_0_val_1_1_fu_114 <= src_kernel_win_0_val_1_0_reg_1080;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter3))) begin
        src_kernel_win_0_val_1_1_lo_reg_1102 <= src_kernel_win_0_val_1_1_fu_114;
        temp_0_i_i_i_059_i_i_1_1_i_reg_1108 <= temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & (1'b0 == ap_reg_ppstg_exitcond_reg_993_pp0_iter2))) begin
        src_kernel_win_0_val_2_1_1_fu_126 <= src_kernel_win_0_val_2_1_fu_122;
        src_kernel_win_0_val_2_1_fu_122 <= src_kernel_win_0_val_2_0_fu_663_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter2))) begin
        temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092 <= temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3;
        tmp_240_0_2_i_reg_1097 <= tmp_240_0_2_i_fu_689_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter4))) begin
        temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114 <= temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3;
        tmp_240_1_2_i_reg_1119 <= tmp_240_1_2_i_fu_755_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter6))) begin
        temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136 <= temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3;
        tmp_240_2_2_i_reg_1141 <= tmp_240_2_2_i_fu_807_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_done_reg) | ((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_293_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st3_fsm_2) & ~(1'b0 == exitcond1_fu_293_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_158) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_314) begin
        ap_sig_cseq_ST_st13_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_105) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_129) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_2_i_reg_967)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_2_i_reg_967)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_i_reg_963)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_762) begin
        if (ap_sig_765) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (ap_sig_763) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_i_reg_963)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_i_reg_963)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_762) begin
        if (ap_sig_765) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (ap_sig_763) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == tmp_194_i_reg_963)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it8) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it8) & ~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))) | ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168))))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~ap_sig_89) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((1'b0 == tmp_23_i_phi_fu_218_p4)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == exitcond1_fu_293_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_3 : begin
            if ((~((1'b1 == ap_reg_ppiten_pp0_it8) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b1 == ap_reg_ppiten_pp0_it7)) & ~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == exitcond_fu_441_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((1'b1 == ap_reg_ppiten_pp0_it8) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b1 == ap_reg_ppiten_pp0_it7)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & ~(((1'b1 == ap_reg_ppiten_pp0_it2) & ap_sig_164) | ((1'b1 == ap_reg_ppiten_pp0_it8) & ap_sig_168)) & ~(1'b0 == exitcond_fu_441_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st13_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st13_fsm_4 : begin
            ap_NS_fsm = ap_ST_st3_fsm_2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_468_p2 = ($signed(ap_const_lv12_FFF) + $signed(tmp_39_cast_i_cast6_fu_437_p1));

always @ (*) begin
    ap_sig_105 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_129 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_158 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_164 = ((~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & (1'b0 == icmp_reg_958) & (p_src_data_stream_V_empty_n == 1'b0)) | (~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0) & ~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949) & (p_src_data_stream_V_empty_n == 1'b0)));
end

always @ (*) begin
    ap_sig_168 = (~(1'b0 == ap_reg_ppstg_or_cond_i_i_i_reg_1020_pp0_iter7) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_sig_23 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_314 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_762 = ((1'b1 == ap_reg_ppiten_pp0_it2) & ~(ap_reg_ppstg_or_cond_i_i_i_i_reg_1008_pp0_iter1 == 1'b0));
end

always @ (*) begin
    ap_sig_763 = ((1'b0 == icmp_reg_958) & ~(1'b0 == tmp_194_i_reg_963));
end

always @ (*) begin
    ap_sig_765 = (~(1'b0 == icmp_reg_958) & ~(1'b0 == tmp_38_i_reg_949));
end

always @ (*) begin
    ap_sig_89 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign brmerge_i_fu_499_p2 = (tmp_43_i_fu_488_p2 | tmp_159_not_i_reg_953);

assign col_assign_1_fu_537_p2 = (tmp_fu_271_p1 - tmp_70_fu_533_p1);

assign col_buf_0_val_0_0_fu_569_p3 = ((ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_22_fu_558_p5);

assign col_buf_0_val_1_0_fu_587_p3 = ((ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_23_fu_576_p5);

assign col_buf_0_val_2_0_fu_605_p3 = ((ap_reg_ppstg_brmerge_i_reg_1013_pp0_iter1[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_24_fu_594_p5);

assign cols_assign_cast_i_cast_fu_251_p1 = cols;

assign exitcond1_fu_293_p2 = ((p_014_0_i_i_i_reg_225 == tmp_s_fu_284_p2) ? 1'b1 : 1'b0);

assign exitcond_fu_441_p2 = ((p_027_0_i_i_i_reg_236 == widthloop_fu_261_p2) ? 1'b1 : 1'b0);

assign i_V_fu_298_p2 = (p_014_0_i_i_i_reg_225 + ap_const_lv11_1);

assign icmp2_fu_462_p2 = ((tmp_66_fu_452_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign icmp_fu_325_p2 = ((tmp_58_fu_315_p4 != ap_const_lv10_0) ? 1'b1 : 1'b0);

assign j_V_fu_446_p2 = (p_027_0_i_i_i_reg_236 + ap_const_lv11_1);

assign k_buf_0_val_3_address0 = tmp_179_i_fu_542_p1;

assign k_buf_0_val_4_address0 = tmp_179_i_fu_542_p1;

assign k_buf_0_val_5_address0 = tmp_179_i_fu_542_p1;

assign or_cond_i_i_i_fu_504_p2 = (icmp_reg_958 & icmp2_fu_462_p2);

assign or_cond_i_i_i_i_fu_493_p2 = (tmp_43_i_fu_488_p2 & rev_fu_482_p2);

assign p_assign_1_fu_519_p3 = ((tmp_69_fu_512_p3[0:0] === 1'b1) ? ap_const_lv11_0 : tmp_35_i_fu_266_p2);

assign p_assign_2_fu_275_p2 = ($signed(ap_const_lv11_7FF) + $signed(rows));

assign p_assign_4_1_i_fu_383_p2 = ($signed(tmp_36_cast_i_cast7_fu_289_p1) + $signed(ap_const_lv12_FFE));

assign p_assign_4_2_i_fu_410_p2 = ($signed(tmp_36_cast_i_cast7_fu_289_p1) + $signed(ap_const_lv12_FFD));

assign p_dst_data_stream_V_din = ((tmp_240_2_2_i_reg_1141[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter7 : temp_0_i_i_i_059_i_i_1_2_1_i_reg_1136);

assign rev_fu_482_p2 = (tmp_68_fu_474_p3 ^ 1'b1);

assign row_assign_7_1_t_i_fu_405_p2 = (tmp_57_fu_280_p1 - tmp_20_fu_398_p3);

assign row_assign_7_2_t_i_fu_432_p2 = (tmp_57_fu_280_p1 - tmp_21_fu_425_p3);

assign rows_assign_cast_i_cast_fu_247_p1 = rows;

assign src_kernel_win_0_val_0_0_fu_635_p3 = ((tmp_216_i_reg_971[0:0] === 1'b1) ? tmp_25_fu_627_p5 : col_buf_0_val_0_0_reg_1049);

assign src_kernel_win_0_val_1_0_fu_649_p3 = ((tmp_216_i_reg_971[0:0] === 1'b1) ? tmp_26_fu_641_p5 : col_buf_0_val_1_0_reg_1057);

assign src_kernel_win_0_val_2_0_fu_663_p3 = ((tmp_216_i_reg_971[0:0] === 1'b1) ? tmp_27_fu_655_p5 : col_buf_0_val_2_0_reg_1065);

assign temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3 = ((tmp_240_0_1_i_fu_675_p2[0:0] === 1'b1) ? src_kernel_win_0_val_2_1_fu_122 : src_kernel_win_0_val_2_1_1_fu_126);

assign temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3 = ((tmp_240_0_2_i_reg_1097[0:0] === 1'b1) ? src_kernel_win_0_val_2_0_reg_1087 : temp_0_i_i_i_059_i_i_1_0_1_i_reg_1092);

assign temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3 = ((tmp_240_1_1_i_fu_745_p2[0:0] === 1'b1) ? src_kernel_win_0_val_1_1_lo_reg_1102 : temp_0_i_i_i_059_i_i_1_1_i_reg_1108);

assign temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3 = ((tmp_240_1_2_i_reg_1119[0:0] === 1'b1) ? ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter5 : temp_0_i_i_i_059_i_i_1_1_1_i_reg_1114);

assign temp_0_i_i_i_059_i_i_1_1_i_fu_725_p3 = ((tmp_240_1_i_fu_719_p2[0:0] === 1'b1) ? src_kernel_win_0_val_1_1_1_fu_118 : temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3);

assign temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3 = ((tmp_240_2_1_i_fu_797_p2[0:0] === 1'b1) ? src_kernel_win_0_val_0_1_lo_reg_1124 : temp_0_i_i_i_059_i_i_1_2_i_reg_1130);

assign temp_0_i_i_i_059_i_i_1_2_i_fu_777_p3 = ((tmp_240_2_i_fu_771_p2[0:0] === 1'b1) ? src_kernel_win_0_val_0_1_1_fu_110 : temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3);

assign tmp_159_not_i_fu_309_p2 = (tmp_38_i_fu_304_p2 ^ 1'b1);

assign tmp_179_i_fu_542_p1 = x_fu_526_p3;

assign tmp_194_2_i_fu_337_p2 = ((p_014_0_i_i_i_reg_225 == ap_const_lv11_1) ? 1'b1 : 1'b0);

assign tmp_194_i_fu_331_p2 = ((p_014_0_i_i_i_reg_225 == ap_const_lv11_0) ? 1'b1 : 1'b0);

assign tmp_20_fu_398_p3 = ((tmp_221_1_i_fu_389_p2[0:0] === 1'b1) ? tmp_64_fu_394_p1 : tmp_57_fu_280_p1);

assign tmp_216_i_fu_343_p2 = ((p_014_0_i_i_i_reg_225 > rows) ? 1'b1 : 1'b0);

assign tmp_219_i_fu_348_p2 = ($signed(tmp_36_cast_i_cast7_fu_289_p1) + $signed(ap_const_lv12_FFF));

assign tmp_21_fu_425_p3 = ((tmp_221_2_i_fu_416_p2[0:0] === 1'b1) ? tmp_65_fu_421_p1 : tmp_57_fu_280_p1);

assign tmp_221_1_i_fu_389_p2 = (($signed(p_assign_4_1_i_fu_383_p2) < $signed(rows_assign_cast_i_cast_fu_247_p1)) ? 1'b1 : 1'b0);

assign tmp_221_2_i_fu_416_p2 = (($signed(p_assign_4_2_i_fu_410_p2) < $signed(rows_assign_cast_i_cast_fu_247_p1)) ? 1'b1 : 1'b0);

assign tmp_221_i_fu_354_p2 = (($signed(tmp_219_i_fu_348_p2) < $signed(rows_assign_cast_i_cast_fu_247_p1)) ? 1'b1 : 1'b0);

assign tmp_23_i_phi_fu_218_p4 = tmp_23_i_reg_214;

assign tmp_240_0_1_i_fu_675_p2 = ((src_kernel_win_0_val_2_1_fu_122 > src_kernel_win_0_val_2_1_1_fu_126) ? 1'b1 : 1'b0);

assign tmp_240_0_2_i_fu_689_p2 = ((src_kernel_win_0_val_2_0_fu_663_p3 > temp_0_i_i_i_059_i_i_1_0_1_i_fu_681_p3) ? 1'b1 : 1'b0);

assign tmp_240_1_1_i_fu_745_p2 = ((src_kernel_win_0_val_1_1_lo_reg_1102 > temp_0_i_i_i_059_i_i_1_1_i_reg_1108) ? 1'b1 : 1'b0);

assign tmp_240_1_2_i_fu_755_p2 = ((ap_reg_ppstg_src_kernel_win_0_val_1_0_reg_1080_pp0_iter4 > temp_0_i_i_i_059_i_i_1_1_1_i_fu_749_p3) ? 1'b1 : 1'b0);

assign tmp_240_1_i_fu_719_p2 = ((src_kernel_win_0_val_1_1_1_fu_118 > temp_0_i_i_i_059_i_i_1_0_2_i_fu_714_p3) ? 1'b1 : 1'b0);

assign tmp_240_2_1_i_fu_797_p2 = ((src_kernel_win_0_val_0_1_lo_reg_1124 > temp_0_i_i_i_059_i_i_1_2_i_reg_1130) ? 1'b1 : 1'b0);

assign tmp_240_2_2_i_fu_807_p2 = ((ap_reg_ppstg_src_kernel_win_0_val_0_0_reg_1073_pp0_iter6 > temp_0_i_i_i_059_i_i_1_2_1_i_fu_801_p3) ? 1'b1 : 1'b0);

assign tmp_240_2_i_fu_771_p2 = ((src_kernel_win_0_val_0_1_1_fu_110 > temp_0_i_i_i_059_i_i_1_1_2_i_fu_766_p3) ? 1'b1 : 1'b0);

assign tmp_24_i_fu_255_p2 = (tmp_23_i_reg_214 ^ 1'b1);

assign tmp_35_i_fu_266_p2 = ($signed(ap_const_lv11_7FF) + $signed(cols));

assign tmp_36_cast_i_cast7_fu_289_p1 = p_014_0_i_i_i_reg_225;

assign tmp_38_i_fu_304_p2 = ((p_014_0_i_i_i_reg_225 < rows) ? 1'b1 : 1'b0);

assign tmp_39_cast_i_cast6_fu_437_p1 = p_027_0_i_i_i_reg_236;

assign tmp_43_i_fu_488_p2 = (($signed(ImagLoc_x_fu_468_p2) < $signed(cols_assign_cast_i_cast_fu_251_p1)) ? 1'b1 : 1'b0);

assign tmp_57_fu_280_p1 = p_assign_2_fu_275_p2[1:0];

assign tmp_58_fu_315_p4 = {{p_014_0_i_i_i_reg_225[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_59_fu_359_p1 = p_assign_2_fu_275_p2[1:0];

assign tmp_60_fu_362_p1 = tmp_219_i_fu_348_p2[1:0];

assign tmp_61_fu_366_p1 = p_assign_2_fu_275_p2[1:0];

assign tmp_62_fu_369_p3 = ((tmp_221_i_fu_354_p2[0:0] === 1'b1) ? tmp_60_fu_362_p1 : tmp_61_fu_366_p1);

assign tmp_63_fu_377_p2 = (tmp_59_fu_359_p1 - tmp_62_fu_369_p3);

assign tmp_64_fu_394_p1 = p_assign_4_1_i_fu_383_p2[1:0];

assign tmp_65_fu_421_p1 = p_assign_4_2_i_fu_410_p2[1:0];

assign tmp_66_fu_452_p4 = {{p_027_0_i_i_i_reg_236[ap_const_lv32_A : ap_const_lv32_1]}};

assign tmp_67_fu_509_p1 = ImagLoc_x_reg_1002[10:0];

assign tmp_68_fu_474_p3 = ImagLoc_x_fu_468_p2[ap_const_lv32_B];

assign tmp_69_fu_512_p3 = ImagLoc_x_reg_1002[ap_const_lv32_B];

assign tmp_70_fu_533_p1 = x_fu_526_p3[1:0];

assign tmp_fu_271_p1 = tmp_35_i_fu_266_p2[1:0];

assign tmp_s_fu_284_p2 = (ap_const_lv11_2 + rows);

assign widthloop_fu_261_p2 = (ap_const_lv11_2 + cols);

assign x_fu_526_p3 = ((or_cond_i_i_i_i_reg_1008[0:0] === 1'b1) ? tmp_67_fu_509_p1 : p_assign_1_fu_519_p3);

endmodule //image_filter_Dilate_0_0_1080_1920_s
