# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cospan/Projects/xilinx_projects/pynq/base/src/constraints/top.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_audio_direct_0_0/system_audio_direct_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_audio_direct_0_0 || ORIG_REF_NAME==system_audio_direct_0_0}]

# IP: bd/system/ip/system_d_axi_pdm_1_0/system_d_axi_pdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_d_axi_pdm_1_0 || ORIG_REF_NAME==system_d_axi_pdm_1_0}]

# IP: bd/system/ip/system_pdm_audio_shutdown_mux_0/system_pdm_audio_shutdown_mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pdm_audio_shutdown_mux_0 || ORIG_REF_NAME==system_pdm_audio_shutdown_mux_0}]

# IP: bd/system/ip/system_pdm_m_clk_mux_0/system_pdm_m_clk_mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pdm_m_clk_mux_0 || ORIG_REF_NAME==system_pdm_m_clk_mux_0}]

# IP: bd/system/ip/system_pwm_audio_o_mux_0/system_pwm_audio_o_mux_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_pwm_audio_o_mux_0 || ORIG_REF_NAME==system_pwm_audio_o_mux_0}]

# IP: bd/system/ip/system_audio_path_sel_0/system_audio_path_sel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_audio_path_sel_0 || ORIG_REF_NAME==system_audio_path_sel_0}]

# IP: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}]

# IP: bd/system/ip/system_concat_interrupts_0/system_concat_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_concat_interrupts_0 || ORIG_REF_NAME==system_concat_interrupts_0}]

# IP: bd/system/ip/system_logic_1_0/system_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_logic_1_0 || ORIG_REF_NAME==system_logic_1_0}]

# IP: bd/system/ip/system_mb_bram_ctrl_1_0/system_mb_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_1_0 || ORIG_REF_NAME==system_mb_bram_ctrl_1_0}]

# IP: bd/system/ip/system_mb_bram_ctrl_2_0/system_mb_bram_ctrl_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_2_0 || ORIG_REF_NAME==system_mb_bram_ctrl_2_0}]

# IP: bd/system/ip/system_mb_bram_ctrl_3_0/system_mb_bram_ctrl_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_3_0 || ORIG_REF_NAME==system_mb_bram_ctrl_3_0}]

# IP: bd/system/ip/system_proc_sys_reset_142M_0/system_proc_sys_reset_142M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_142M_0 || ORIG_REF_NAME==system_proc_sys_reset_142M_0}]

# IP: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}]

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}]

# IP: bd/system/ip/system_processing_system7_0_axi_periph_0/system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==system_processing_system7_0_axi_periph_0}]

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4}]

# IP: bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgbleds_gpio_0 || ORIG_REF_NAME==system_rgbleds_gpio_0}]

# IP: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}]

# IP: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}]

# IP: bd/system/ip/system_axi_dynclk_0_0/system_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dynclk_0_0 || ORIG_REF_NAME==system_axi_dynclk_0_0}]

# IP: bd/system/ip/system_axi_gpio_video_0/system_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_video_0 || ORIG_REF_NAME==system_axi_gpio_video_0}]

# IP: bd/system/ip/system_axi_mem_intercon_1/system_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_1 || ORIG_REF_NAME==system_axi_mem_intercon_1}]

# IP: bd/system/ip/system_xbar_6/system_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_6 || ORIG_REF_NAME==system_xbar_6}]

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}]

# IP: bd/system/ip/system_dvi2rgb_0_0/system_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dvi2rgb_0_0 || ORIG_REF_NAME==system_dvi2rgb_0_0}]

# IP: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}]

# IP: bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}]

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}]

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0}]

# IP: bd/system/ip/system_v_tc_1_0/system_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_1_0 || ORIG_REF_NAME==system_v_tc_1_0}]

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_mb_bram_ctrl_1_bram_1/system_mb_bram_ctrl_1_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_1_bram_1 || ORIG_REF_NAME==system_mb_bram_ctrl_1_bram_1}]

# IP: bd/system/ip/system_mb_bram_ctrl_2_bram_1/system_mb_bram_ctrl_2_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_2_bram_1 || ORIG_REF_NAME==system_mb_bram_ctrl_2_bram_1}]

# IP: bd/system/ip/system_mb_bram_ctrl_3_bram_1_1/system_mb_bram_ctrl_3_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_bram_ctrl_3_bram_1 || ORIG_REF_NAME==system_mb_bram_ctrl_3_bram_1}]

# IP: bd/system/ip/system_rst_processing_system7_0_166M_2/system_rst_processing_system7_0_166M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_166M_2 || ORIG_REF_NAME==system_rst_processing_system7_0_166M_2}]

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2}]

# IP: bd/system/ip/system_xlconstant_1_0/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0}]

# IP: bd/system/ip/system_xlconstant_1_1/system_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_1 || ORIG_REF_NAME==system_xlconstant_1_1}]

# IP: bd/system/ip/system_xlconstant_2_0/system_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_2_0 || ORIG_REF_NAME==system_xlconstant_2_0}]

# IP: bd/system/ip/system_xlconstant_3_0/system_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_3_0 || ORIG_REF_NAME==system_xlconstant_3_0}]

# IP: bd/system/ip/system_xlconstant_4_0/system_xlconstant_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_4_0 || ORIG_REF_NAME==system_xlconstant_4_0}]

# IP: bd/system/ip/system_xlconstant_5_0/system_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_5_0 || ORIG_REF_NAME==system_xlconstant_5_0}]

# IP: bd/system/ip/system_xlconstant_6_0/system_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_6_0 || ORIG_REF_NAME==system_xlconstant_6_0}]

# IP: bd/system/ip/system_xlconstant_8_0/system_xlconstant_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_8_0 || ORIG_REF_NAME==system_xlconstant_8_0}]

# IP: bd/system/ip/system_xlconstant_9_0/system_xlconstant_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_9_0 || ORIG_REF_NAME==system_xlconstant_9_0}]

# IP: bd/system/ip/system_xlconstant_10_0/system_xlconstant_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_10_0 || ORIG_REF_NAME==system_xlconstant_10_0}]

# IP: bd/system/ip/system_xlconstant_11_0/system_xlconstant_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_11_0 || ORIG_REF_NAME==system_xlconstant_11_0}]

# IP: bd/system/ip/system_xlconstant_12_1/system_xlconstant_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_12_1 || ORIG_REF_NAME==system_xlconstant_12_1}]

# IP: bd/system/ip/system_xlconstant_13_0/system_xlconstant_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_13_0 || ORIG_REF_NAME==system_xlconstant_13_0}]

# IP: bd/system/ip/system_xlconstant_14_0/system_xlconstant_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_14_0 || ORIG_REF_NAME==system_xlconstant_14_0}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1}]

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2}]

# IP: bd/system/ip/system_auto_pc_3/system_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_3 || ORIG_REF_NAME==system_auto_pc_3}]

# IP: bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_4 || ORIG_REF_NAME==system_auto_pc_4}]

# IP: bd/system/ip/system_auto_pc_5/system_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_5 || ORIG_REF_NAME==system_auto_pc_5}]

# IP: bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_6 || ORIG_REF_NAME==system_auto_pc_6}]

# IP: bd/system/ip/system_auto_pc_7/system_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_7 || ORIG_REF_NAME==system_auto_pc_7}]

# IP: bd/system/ip/system_auto_pc_8/system_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_8 || ORIG_REF_NAME==system_auto_pc_8}]

# IP: bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_9 || ORIG_REF_NAME==system_auto_pc_9}]

# IP: bd/system/ip/system_auto_pc_10/system_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_10 || ORIG_REF_NAME==system_auto_pc_10}]

# IP: bd/system/ip/system_auto_cc_0_1/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}]

# IP: bd/system/ip/system_auto_pc_11/system_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_11 || ORIG_REF_NAME==system_auto_pc_11}]

# IP: bd/system/ip/system_auto_pc_12/system_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_12 || ORIG_REF_NAME==system_auto_pc_12}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_btns_gpio_0 || ORIG_REF_NAME==system_btns_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mb_bram_ctrl_1_0/system_mb_bram_ctrl_1_0_ooc.xdc

# XDC: bd/system/ip/system_mb_bram_ctrl_2_0/system_mb_bram_ctrl_2_0_ooc.xdc

# XDC: bd/system/ip/system_mb_bram_ctrl_3_0/system_mb_bram_ctrl_3_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_142M_0/system_proc_sys_reset_142M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_142M_0 || ORIG_REF_NAME==system_proc_sys_reset_142M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_142M_0/system_proc_sys_reset_142M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_142M_0 || ORIG_REF_NAME==system_proc_sys_reset_142M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_142M_0/system_proc_sys_reset_142M_0_ooc.xdc

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_pixelclk_0 || ORIG_REF_NAME==system_proc_sys_reset_pixelclk_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_proc_sys_reset_pixelclk_0/system_proc_sys_reset_pixelclk_0_ooc.xdc

# XDC: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_xbar_4/system_xbar_4_ooc.xdc

# XDC: bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgbleds_gpio_0 || ORIG_REF_NAME==system_rgbleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgbleds_gpio_0 || ORIG_REF_NAME==system_rgbleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==system_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_100M_0/system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0_ooc.xdc

# XDC: bd/system/ip/system_swsleds_gpio_0/system_swsleds_gpio_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_swsleds_gpio_0 || ORIG_REF_NAME==system_swsleds_gpio_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_video_0/system_axi_gpio_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_video_0 || ORIG_REF_NAME==system_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_video_0/system_axi_gpio_video_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_video_0/system_axi_gpio_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_video_0 || ORIG_REF_NAME==system_axi_gpio_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_xbar_6/system_xbar_6_ooc.xdc

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc

# XDC: bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dvi2rgb_0_0 || ORIG_REF_NAME==system_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_ooc.xdc

# XDC: bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_hdmi_out_hpd_video_0 || ORIG_REF_NAME==system_hdmi_out_hpd_video_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/system/ip/system_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc

# XDC: bd/system/ip/system_v_tc_1_0/system_v_tc_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_tc_1_0 || ORIG_REF_NAME==system_v_tc_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_v_tc_1_0/system_v_tc_1_0_ooc.xdc

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/system/ip/system_mb_bram_ctrl_1_bram_1/system_mb_bram_ctrl_1_bram_1_ooc.xdc

# XDC: bd/system/ip/system_mb_bram_ctrl_2_bram_1/system_mb_bram_ctrl_2_bram_1_ooc.xdc

# XDC: bd/system/ip/system_mb_bram_ctrl_3_bram_1_1/system_mb_bram_ctrl_3_bram_1_ooc.xdc

# XDC: bd/system/ip/system_rst_processing_system7_0_166M_2/system_rst_processing_system7_0_166M_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_166M_2 || ORIG_REF_NAME==system_rst_processing_system7_0_166M_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_166M_2/system_rst_processing_system7_0_166M_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_processing_system7_0_166M_2 || ORIG_REF_NAME==system_rst_processing_system7_0_166M_2}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_processing_system7_0_166M_2/system_rst_processing_system7_0_166M_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_7/system_auto_pc_7_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_10/system_auto_pc_10_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0_1/system_auto_cc_0_ooc.xdc

# XDC: bd/system/ip/system_auto_cc_0_1/system_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_pc_11/system_auto_pc_11_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_12/system_auto_pc_12_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/system/system_ooc.xdc
