
COMMAND=/home/cospan/Projects/Xilinx/Vivado_HLS/2016.4/bin/vivado_hls

default: sim

.PHONY: sim rtl cosim package clean

sim:
	@echo "sim"
	${COMMAND} -f tcl/sim.tcl

rtl:
	@echo "rtl"
	@echo "Not Done Yet!"

cosim:
	@echo "cosim"
	@echo "Not Done Yet!"

package:
	@echo "package"
	@echo "Not Done Yet!"

clean:
	@echo "clean"
	@echo "Not Done Yet!"

