-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.1
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_AXIvideo2Mat is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    video_in_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    video_in_TVALID : IN STD_LOGIC;
    video_in_TREADY : OUT STD_LOGIC;
    video_in_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    video_in_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    video_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    video_in_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    rows : IN STD_LOGIC_VECTOR (10 downto 0);
    cols : IN STD_LOGIC_VECTOR (10 downto 0);
    img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_0_V_full_n : IN STD_LOGIC;
    img_data_stream_0_V_write : OUT STD_LOGIC;
    img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_1_V_full_n : IN STD_LOGIC;
    img_data_stream_1_V_write : OUT STD_LOGIC );
end;


architecture behav of image_filter_AXIvideo2Mat is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_pp1_stg0_fsm_4 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_st7_fsm_5 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_st8_fsm_6 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_true : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_25 : BOOLEAN;
    signal video_in_TDATA_blk_n : STD_LOGIC;
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_57 : BOOLEAN;
    signal ap_sig_cseq_ST_pp1_stg0_fsm_4 : STD_LOGIC;
    signal ap_sig_64 : BOOLEAN;
    signal ap_reg_ppiten_pp1_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp1_it1 : STD_LOGIC := '0';
    signal exitcond4_i_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_5 : STD_LOGIC;
    signal ap_sig_84 : BOOLEAN;
    signal img_data_stream_0_V_blk_n : STD_LOGIC;
    signal exitcond4_i_reg_383 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_data_stream_1_V_blk_n : STD_LOGIC;
    signal eol_reg_171 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_i_reg_182 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_8_i_reg_193 : STD_LOGIC_VECTOR (10 downto 0);
    signal eol_i_reg_204 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_2_i_reg_216 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_229 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_113 : BOOLEAN;
    signal tmp_data_V_reg_354 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_last_V_reg_362 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond3_i_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_132 : BOOLEAN;
    signal i_V_fu_299_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_378 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_137 : BOOLEAN;
    signal ap_sig_144 : BOOLEAN;
    signal j_V_fu_310_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_325_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_396 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_401 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_160 : BOOLEAN;
    signal axi_last_V_3_i_reg_241 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V1_i_reg_140 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st8_fsm_6 : STD_LOGIC;
    signal ap_sig_178 : BOOLEAN;
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_185 : BOOLEAN;
    signal axi_data_V_3_i_reg_253 : STD_LOGIC_VECTOR (15 downto 0);
    signal axi_data_V1_i_reg_150 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_i_reg_160 : STD_LOGIC_VECTOR (10 downto 0);
    signal eol_phi_fu_174_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_i_phi_fu_185_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal eol_i_phi_fu_208_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_phiprechg_axi_last_V_2_i_reg_216pp1_it0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_s_phi_fu_233_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal eol_2_i_reg_265 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_1_i_fu_92 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_user_V_fu_285_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_77 : BOOLEAN;
    signal ap_sig_205 : BOOLEAN;
    signal ap_sig_152 : BOOLEAN;
    signal ap_sig_219 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = exitcond3_i_fu_294_p2)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp1_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0)))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then 
                    ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_ppiten_pp1_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0))))) then 
                    ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V1_i_reg_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                axi_data_V1_i_reg_150 <= tmp_data_V_reg_354;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                axi_data_V1_i_reg_150 <= axi_data_V_3_i_reg_253;
            end if; 
        end if;
    end process;

    axi_data_V_1_i_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                axi_data_V_1_i_reg_182 <= p_Val2_s_reg_229;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then 
                axi_data_V_1_i_reg_182 <= axi_data_V1_i_reg_150;
            end if; 
        end if;
    end process;

    axi_data_V_3_i_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0)))) then 
                axi_data_V_3_i_reg_253 <= axi_data_V_1_i_phi_fu_185_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_i_reg_265) and not(ap_sig_160))) then 
                axi_data_V_3_i_reg_253 <= video_in_TDATA;
            end if; 
        end if;
    end process;

    axi_last_V1_i_reg_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                axi_last_V1_i_reg_140 <= tmp_last_V_reg_362;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                axi_last_V1_i_reg_140 <= axi_last_V_3_i_reg_241;
            end if; 
        end if;
    end process;

    axi_last_V_2_i_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_152) then
                if (ap_sig_205) then 
                    axi_last_V_2_i_reg_216 <= eol_phi_fu_174_p4;
                elsif (ap_sig_77) then 
                    axi_last_V_2_i_reg_216 <= video_in_TLAST;
                elsif ((ap_true = ap_true)) then 
                    axi_last_V_2_i_reg_216 <= ap_reg_phiprechg_axi_last_V_2_i_reg_216pp1_it0;
                end if;
            end if; 
        end if;
    end process;

    axi_last_V_3_i_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0)))) then 
                axi_last_V_3_i_reg_241 <= eol_phi_fu_174_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_i_reg_265) and not(ap_sig_160))) then 
                axi_last_V_3_i_reg_241 <= video_in_TLAST;
            end if; 
        end if;
    end process;

    eol_2_i_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0)))) then 
                eol_2_i_reg_265 <= eol_i_phi_fu_208_p4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_i_reg_265) and not(ap_sig_160))) then 
                eol_2_i_reg_265 <= video_in_TLAST;
            end if; 
        end if;
    end process;

    eol_i_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                eol_i_reg_204 <= axi_last_V_2_i_reg_216;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then 
                eol_i_reg_204 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    eol_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                eol_reg_171 <= axi_last_V_2_i_reg_216;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then 
                eol_reg_171 <= axi_last_V1_i_reg_140;
            end if; 
        end if;
    end process;

    p_8_i_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                p_8_i_reg_193 <= j_V_fu_310_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then 
                p_8_i_reg_193 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_152) then
                if (ap_sig_205) then 
                    p_Val2_s_reg_229 <= axi_data_V_1_i_phi_fu_185_p4;
                elsif (ap_sig_77) then 
                    p_Val2_s_reg_229 <= video_in_TDATA;
                elsif ((ap_true = ap_true)) then 
                    p_Val2_s_reg_229 <= ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0;
                end if;
            end if; 
        end if;
    end process;

    p_i_reg_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                p_i_reg_160 <= ap_const_lv11_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st8_fsm_6)) then 
                p_i_reg_160 <= i_V_reg_378;
            end if; 
        end if;
    end process;

    sof_1_i_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
                sof_1_i_fu_92 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                sof_1_i_fu_92 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then
                exitcond4_i_reg_383 <= exitcond4_i_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then
                i_V_reg_378 <= i_V_fu_299_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then
                tmp_4_reg_401 <= p_Val2_s_phi_fu_233_p4(15 downto 8);
                tmp_reg_396 <= tmp_fu_325_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((video_in_TVALID = ap_const_logic_0)))) then
                tmp_data_V_reg_354 <= video_in_TDATA;
                tmp_last_V_reg_362 <= video_in_TLAST;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, video_in_TVALID, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond4_i_fu_305_p2, ap_sig_113, exitcond3_i_fu_294_p2, ap_sig_137, ap_sig_144, ap_sig_160, eol_2_i_reg_265, tmp_user_V_fu_285_p1)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_113)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((not((video_in_TVALID = ap_const_logic_0)) and (ap_const_lv1_0 = tmp_user_V_fu_285_p1))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                elsif ((not((video_in_TVALID = ap_const_logic_0)) and not((ap_const_lv1_0 = tmp_user_V_fu_285_p1)))) then
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                end if;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                if (not((ap_const_lv1_0 = exitcond3_i_fu_294_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                end if;
            when ap_ST_pp1_stg0_fsm_4 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))) and not((exitcond4_i_fu_305_p2 = ap_const_lv1_0)))) then
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                else
                    ap_NS_fsm <= ap_ST_pp1_stg0_fsm_4;
                end if;
            when ap_ST_st7_fsm_5 => 
                if (((ap_const_lv1_0 = eol_2_i_reg_265) and not(ap_sig_160))) then
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                elsif ((not(ap_sig_160) and not((ap_const_lv1_0 = eol_2_i_reg_265)))) then
                    ap_NS_fsm <= ap_ST_st8_fsm_6;
                else
                    ap_NS_fsm <= ap_ST_st7_fsm_5;
                end if;
            when ap_ST_st8_fsm_6 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;

    ap_done_assign_proc : process(ap_done_reg, exitcond3_i_fu_294_p2, ap_sig_cseq_ST_st4_fsm_3)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = exitcond3_i_fu_294_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(exitcond3_i_fu_294_p2, ap_sig_cseq_ST_st4_fsm_3)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = exitcond3_i_fu_294_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_reg_phiprechg_axi_last_V_2_i_reg_216pp1_it0 <= "X";
    ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0 <= "XXXXXXXXXXXXXXXX";

    ap_sig_113_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_113 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_sig_132_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_132 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    ap_sig_137_assign_proc : process(video_in_TVALID, exitcond4_i_fu_305_p2, brmerge_i_fu_319_p2)
    begin
                ap_sig_137 <= ((exitcond4_i_fu_305_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_i_fu_319_p2) and (video_in_TVALID = ap_const_logic_0));
    end process;


    ap_sig_144_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, exitcond4_i_reg_383)
    begin
                ap_sig_144 <= (((ap_const_lv1_0 = exitcond4_i_reg_383) and (img_data_stream_0_V_full_n = ap_const_logic_0)) or ((ap_const_lv1_0 = exitcond4_i_reg_383) and (img_data_stream_1_V_full_n = ap_const_logic_0)));
    end process;


    ap_sig_152_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, ap_sig_137, ap_sig_144)
    begin
                ap_sig_152 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))));
    end process;


    ap_sig_160_assign_proc : process(video_in_TVALID, eol_2_i_reg_265)
    begin
                ap_sig_160 <= ((ap_const_lv1_0 = eol_2_i_reg_265) and (video_in_TVALID = ap_const_logic_0));
    end process;


    ap_sig_178_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_178 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    ap_sig_185_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_185 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    ap_sig_205_assign_proc : process(exitcond4_i_fu_305_p2, brmerge_i_fu_319_p2)
    begin
                ap_sig_205 <= ((exitcond4_i_fu_305_p2 = ap_const_lv1_0) and not((ap_const_lv1_0 = brmerge_i_fu_319_p2)));
    end process;


    ap_sig_219_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, exitcond4_i_fu_305_p2)
    begin
                ap_sig_219 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0));
    end process;


    ap_sig_25_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_25 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    ap_sig_57_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_57 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    ap_sig_64_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_64 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    ap_sig_77_assign_proc : process(exitcond4_i_fu_305_p2, brmerge_i_fu_319_p2)
    begin
                ap_sig_77 <= ((exitcond4_i_fu_305_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_i_fu_319_p2));
    end process;


    ap_sig_84_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_84 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    ap_sig_cseq_ST_pp1_stg0_fsm_4_assign_proc : process(ap_sig_64)
    begin
        if (ap_sig_64) then 
            ap_sig_cseq_ST_pp1_stg0_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp1_stg0_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_25)
    begin
        if (ap_sig_25) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_57)
    begin
        if (ap_sig_57) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_185)
    begin
        if (ap_sig_185) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_132)
    begin
        if (ap_sig_132) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st7_fsm_5_assign_proc : process(ap_sig_84)
    begin
        if (ap_sig_84) then 
            ap_sig_cseq_ST_st7_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_cseq_ST_st8_fsm_6_assign_proc : process(ap_sig_178)
    begin
        if (ap_sig_178) then 
            ap_sig_cseq_ST_st8_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st8_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;


    axi_data_V_1_i_phi_fu_185_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383, axi_data_V_1_i_reg_182, p_Val2_s_reg_229)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383))) then 
            axi_data_V_1_i_phi_fu_185_p4 <= p_Val2_s_reg_229;
        else 
            axi_data_V_1_i_phi_fu_185_p4 <= axi_data_V_1_i_reg_182;
        end if; 
    end process;

    brmerge_i_fu_319_p2 <= (sof_1_i_fu_92 or eol_i_phi_fu_208_p4);

    eol_i_phi_fu_208_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383, eol_i_reg_204, axi_last_V_2_i_reg_216)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383))) then 
            eol_i_phi_fu_208_p4 <= axi_last_V_2_i_reg_216;
        else 
            eol_i_phi_fu_208_p4 <= eol_i_reg_204;
        end if; 
    end process;


    eol_phi_fu_174_p4_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383, eol_reg_171, axi_last_V_2_i_reg_216)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383))) then 
            eol_phi_fu_174_p4 <= axi_last_V_2_i_reg_216;
        else 
            eol_phi_fu_174_p4 <= eol_reg_171;
        end if; 
    end process;

    exitcond3_i_fu_294_p2 <= "1" when (p_i_reg_160 = rows) else "0";
    exitcond4_i_fu_305_p2 <= "1" when (p_8_i_reg_193 = cols) else "0";
    i_V_fu_299_p2 <= std_logic_vector(unsigned(p_i_reg_160) + unsigned(ap_const_lv11_1));

    img_data_stream_0_V_blk_n_assign_proc : process(img_data_stream_0_V_full_n, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383))) then 
            img_data_stream_0_V_blk_n <= img_data_stream_0_V_full_n;
        else 
            img_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_0_V_din <= tmp_reg_396;

    img_data_stream_0_V_write_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383, ap_sig_137, ap_sig_144)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
            img_data_stream_0_V_write <= ap_const_logic_1;
        else 
            img_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_1_V_blk_n_assign_proc : process(img_data_stream_1_V_full_n, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383))) then 
            img_data_stream_1_V_blk_n <= img_data_stream_1_V_full_n;
        else 
            img_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_1_V_din <= tmp_4_reg_401;

    img_data_stream_1_V_write_assign_proc : process(ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond4_i_reg_383, ap_sig_137, ap_sig_144)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and (ap_const_lv1_0 = exitcond4_i_reg_383) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144))))) then 
            img_data_stream_1_V_write <= ap_const_logic_1;
        else 
            img_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_310_p2 <= std_logic_vector(unsigned(p_8_i_reg_193) + unsigned(ap_const_lv11_1));

    p_Val2_s_phi_fu_233_p4_assign_proc : process(video_in_TDATA, brmerge_i_fu_319_p2, axi_data_V_1_i_phi_fu_185_p4, ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0, ap_sig_219)
    begin
        if (ap_sig_219) then
            if (not((ap_const_lv1_0 = brmerge_i_fu_319_p2))) then 
                p_Val2_s_phi_fu_233_p4 <= axi_data_V_1_i_phi_fu_185_p4;
            elsif ((ap_const_lv1_0 = brmerge_i_fu_319_p2)) then 
                p_Val2_s_phi_fu_233_p4 <= video_in_TDATA;
            else 
                p_Val2_s_phi_fu_233_p4 <= ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0;
            end if;
        else 
            p_Val2_s_phi_fu_233_p4 <= ap_reg_phiprechg_p_Val2_s_reg_229pp1_it0;
        end if; 
    end process;

    tmp_fu_325_p1 <= p_Val2_s_phi_fu_233_p4(8 - 1 downto 0);
    tmp_user_V_fu_285_p1 <= video_in_TUSER;

    video_in_TDATA_blk_n_assign_proc : process(video_in_TVALID, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, exitcond4_i_fu_305_p2, brmerge_i_fu_319_p2, ap_sig_cseq_ST_st7_fsm_5, eol_2_i_reg_265)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_i_fu_319_p2)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_i_reg_265)))) then 
            video_in_TDATA_blk_n <= video_in_TVALID;
        else 
            video_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    video_in_TREADY_assign_proc : process(video_in_TVALID, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_pp1_stg0_fsm_4, ap_reg_ppiten_pp1_it0, ap_reg_ppiten_pp1_it1, exitcond4_i_fu_305_p2, brmerge_i_fu_319_p2, ap_sig_cseq_ST_st7_fsm_5, ap_sig_137, ap_sig_144, ap_sig_160, eol_2_i_reg_265)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((video_in_TVALID = ap_const_logic_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_5) and (ap_const_lv1_0 = eol_2_i_reg_265) and not(ap_sig_160)) or ((ap_const_logic_1 = ap_sig_cseq_ST_pp1_stg0_fsm_4) and (ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and (exitcond4_i_fu_305_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = brmerge_i_fu_319_p2) and not((((ap_const_logic_1 = ap_reg_ppiten_pp1_it0) and ap_sig_137) or ((ap_const_logic_1 = ap_reg_ppiten_pp1_it1) and ap_sig_144)))))) then 
            video_in_TREADY <= ap_const_logic_1;
        else 
            video_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

end behav;
